import {
  useEffect,
  useMemo,
  useState,
} from 'react'
import {
  STITCH_LINE_TYPE_ID,
} from './cad/line-types'
import {
  saveCatalogRepository,
} from './templates/catalog-repository'

import { detectOutlines, type OutlineChain } from './ops/outline-detection'
import type {
  ResolvedThemeMode,
} from './editor-types'
import {
  toolLabel,
} from './editor-utils'
import { useEditorDerivedState } from './hooks/useEditorDerivedState'
import { useExportActions } from './hooks/useExportActions'
import { useLayerActions } from './hooks/useLayerActions'
import { useConstraintActions } from './hooks/useConstraintActions'
import { useStitchActions } from './hooks/useStitchActions'
import { useFileActions } from './hooks/useFileActions'
import { useTemplateActions } from './hooks/useTemplateActions'
import { useTracingActions } from './hooks/useTracingActions'
import { useBackdropActions } from './hooks/useBackdropActions'
import { useMobileActions } from './hooks/useMobileActions'
import { useResponsiveLayout } from './hooks/useResponsiveLayout'
import { useEditorAutomationEffects } from './hooks/useEditorAutomationEffects'
import { useLineTypeActions } from './hooks/useLineTypeActions'
import { useLayerColorActions } from './hooks/useLayerColorActions'
import { useEditorConsistencyEffects } from './hooks/useEditorConsistencyEffects'
import { useCombinedDraftAndSnapElement } from './hooks/useDraftCanvasElements'
import { useHardwareMarkerActions } from './hooks/useHardwareMarkerActions'
import { useEditorLayoutFlags } from './hooks/useEditorLayoutFlags'
import { useLoadedDocumentActions } from './hooks/useLoadedDocumentActions'
import { useEditorPreviewPaneProps } from './hooks/useEditorPreviewPaneProps'
import { useSketchGroupActions } from './hooks/useSketchGroupActions'
import { useHistoryActions } from './hooks/useHistoryActions'
import { useEditorStateActions } from './hooks/useEditorStateActions'
import { useEditorStatusBarProps } from './hooks/useEditorStatusBarProps'
import { useSelectionActions } from './hooks/useSelectionActions'
import { useTransformActions } from './hooks/useTransformActions'
import { useAutoSave } from './hooks/useAutoSave'
import { useThemeActions } from './hooks/useThemeActions'
import { useEditorPanelState } from './hooks/useEditorPanelState'
import { useEditorViewport } from './hooks/useEditorViewport'
import { useEditorLayers } from './hooks/useEditorLayers'
import { useEditorTools } from './hooks/useEditorTools'
import { useEditorDocumentState } from './hooks/useEditorDocumentState'
import { useEditorUIState } from './hooks/useEditorUIState'
import { useEditorSelectionState } from './hooks/useEditorSelectionState'
import { useEditorRepositoryState } from './hooks/useEditorRepositoryState'
import { useAiBuilderActions } from './hooks/useAiBuilderActions'
import { useGeometryEditingActions } from './hooks/useGeometryEditingActions'
import { type StitchSimulatorSettings } from './ops/stitch-simulator-ops'
import { loadStitchSimulatorSettings } from './ops/stitch-simulator-settings'
import {
  loadBoxStitchHelperSettings,
  type BoxStitchHelperSettings,
} from './ops/box-stitch-settings'
import { useWorkbenchShellState } from './workbench/useWorkbenchShellState'
import { useWorkbenchRouteSync } from './workbench/useWorkbenchRouteSync'
import { usePatternPieceSelection } from './state/selectors/usePatternPieceSelection'
import { usePatternPieceCommands } from './controllers/usePatternPieceCommands'
import { usePrintPreviewState } from './state/selectors/usePrintPreviewState'
import { useEditorCreationController } from './controllers/useEditorCreationController'
import { useEditorDocumentBootstrap } from './controllers/useEditorDocumentBootstrap'
import { useEditorWorkbenchController } from './controllers/useEditorWorkbenchController'
import { buildCanvasPaneParams } from './modules/canvas/buildCanvasPaneParams'
import { useEditorCanvasController } from './modules/canvas/useEditorCanvasController'
import { useEditorGlobalShortcuts } from './modules/canvas/useEditorGlobalShortcuts'
import { useEditorOverlayViewModel } from './modules/overlays/useEditorOverlayViewModel'
import {
  buildWorkbenchProps,
  buildWorkbenchThreeWorkspaceProps,
} from './modules/workbench/buildWorkbenchShellViewModels'
import { useEditorScreenRefs } from './controllers/useEditorScreenRefs'
import {
  buildDocumentInspectorProps,
  buildPieceInspectorContentProps,
  buildSelectionInspectorProps,
} from './view-models/buildWorkbenchInspectorViewModels'
import { useEditorTopbarViewModel } from './view-models/useEditorTopbarViewModel'
import { useEditorDocumentCommands } from './useEditorDocumentCommands'
import { useEditorAssetCommands } from './useEditorAssetCommands'
import { useEditorWorkbenchProps } from './useEditorWorkbenchProps'

export type EditorScreenLayoutModel = {
  isMobileLayout: boolean
  resolvedThemeMode: ResolvedThemeMode
  shouldLoadThreeWorkbench: boolean
}

export type { EditorOverlayProps } from './controllers/buildEditorOverlayProps'

export function useEditorScreenController() {
  // Document state: shapes, constraints, layers, overlays, etc.
  const {
    documentName, setDocumentName,
    lineTypes, setLineTypes,
    activeLineTypeId, setActiveLineTypeId,
    shapes, setShapes,
    foldLines, setFoldLines,
    stitchHoles, setStitchHoles,
    sketchGroups, setSketchGroups,
    activeSketchGroupId, setActiveSketchGroupId,
    constraints, setConstraints,
    patternPieces, setPatternPieces,
    pieceGrainlines, setPieceGrainlines,
    pieceLabels, setPieceLabels,
    piecePlacementLabels, setPiecePlacementLabels,
    piecePlacements3d, setPiecePlacements3d,
    seamConnections, setSeamConnections,
    seamAllowances, setSeamAllowances,
    pieceNotches, setPieceNotches,
    hardwareMarkers, setHardwareMarkers,
    dimensionLines, setDimensionLines,
    printAreas, setPrintAreas,
    snapSettings, setSnapSettings,
    showAnnotations, setShowAnnotations,
    tracingOverlays, setTracingOverlays,
    activeTracingOverlayId, setActiveTracingOverlayId,
    backdrops, setBackdrops,
    activeBackdropId, setActiveBackdropId,
    projectMemo, setProjectMemo,
    stitchAlwaysShapeIds, setStitchAlwaysShapeIds,
    stitchThreadColor, setStitchThreadColor,
    threePreviewSettings, setThreePreviewSettings,
    avatars, setAvatars,
    threeTextureSource, setThreeTextureSource,
    threeTextureShapeIds, setThreeTextureShapeIds,
    showCanvasRuler, setShowCanvasRuler,
    showDimensions, setShowDimensions,
  } = useEditorDocumentState()

  // UI state: layout, modals, theme, display settings
  const {
    setStatus,
    showThreePreview, setShowThreePreview,
    isMobileLayout, setIsMobileLayout,
    mobileViewMode, setMobileViewMode,
    showMobileMenu, setShowMobileMenu,
    mobileOptionsTab, setMobileOptionsTab,
    showPrecisionModal, setShowPrecisionModal,
    showProjectMemoModal, setShowProjectMemoModal,
    showNestingModal, setShowNestingModal,
    desktopRibbonTab,
    workbenchRibbonTab, setWorkbenchRibbonTab,
    workspaceMode, setWorkspaceMode,
    secondaryPreviewMode, setSecondaryPreviewMode,
    mobileLayerAction,
    mobileFileAction,
    displayUnit, setDisplayUnit,
    gridSpacing, setGridSpacing,
    legendMode, setLegendMode,
    sketchWorkspaceMode, setSketchWorkspaceMode,
    selectedPresetId, setSelectedPresetId,
    themeMode, setThemeMode,
    systemThemeMode, setSystemThemeMode,
    loadedFontUrl, setLoadedFontUrl,
    constraintSuggestions, setConstraintSuggestions,
    autoConstraintSettings,
    showStitchSimulatorModal, setShowStitchSimulatorModal,
    showBoxStitchHelperModal, setShowBoxStitchHelperModal,
    showBoxStitchModal, setShowBoxStitchModal,
    showMandalaModal, setShowMandalaModal,
    showWizardModal, setShowWizardModal,
    showBackdropModal, setShowBackdropModal,
    showLetterStampModal, setShowLetterStampModal,
    showChangeShapeSizeModal, setShowChangeShapeSizeModal,
    showBezierOffsetLines, setShowBezierOffsetLines,
    customRotationPivot, setCustomRotationPivot,
    customSnapPoint, setCustomSnapPoint,
    showSpecifyRotationModal, setShowSpecifyRotationModal,
    showSpecifyScaleModal, setShowSpecifyScaleModal,
    specifyScaleModalAxis, setSpecifyScaleModalAxis,
    showFontListModal, setShowFontListModal,
    fontList, setFontList,
    autoSaveEnabled, setAutoSaveEnabled,
    reverseZoomDirection, setReverseZoomDirection,
    incrementalSelection, setIncrementalSelection,
    mentoriWithoutCtrl, setMentoriWithoutCtrl,
    lineToolConstraint, setLineToolConstraint,
    leatherSimEnabled,
    setTranslationMap,
    showGrid, setShowGrid,
    gridBackgroundMode, setGridBackgroundMode,
    showLengthAdjustModal, setShowLengthAdjustModal,
    showOptionsModal, setShowOptionsModal,
    leatherSimTextureRotationDeg,
    exportIncludeText, setExportIncludeText,
    exportIncludeTemplateMetadata, setExportIncludeTemplateMetadata,
  } = useEditorUIState()

  // Selection state: selected shapes, stitch holes, hardware markers, clipboard
  const {
    selectedShapeIds, setSelectedShapeIds,
    selectedStitchHoleId, setSelectedStitchHoleId,
    selectedHardwareMarkerId, setSelectedHardwareMarkerId,
    clipboardPayload, setClipboardPayload,
  } = useEditorSelectionState()

  // Repository state: templates, catalogs
  const {
    templateRepository, setTemplateRepository,
    selectedTemplateEntryId, setSelectedTemplateEntryId,
    catalogRepository, setCatalogRepository,
    bundledCatalogRepository,
    selectedCatalogShopId, setSelectedCatalogShopId,
  } = useEditorRepositoryState()
  const {
    setShowLayerColorModal,
    setShowExportOptionsModal,
    setExportOnlySelectedShapes,
    setExportOnlyVisibleLineTypes,
    setExportRoleFilters,
    setExportForceSolidStrokes,
    setExportStitchHoleRenderMode,
    setExportStitchDotRadiusMm,
    setDxfFlipY,
    setDxfVersion,
    setShowTracingModal,
    setShowPatternToolsModal,
    setShowAiBuilderModal,
    setShowHelpModal,
    setShowTemplateRepositoryModal,
    showPrintAreas,
    setShowPrintAreas,
    setShowPrintPreviewModal,
  } = useEditorPanelState()
  const {
    layers,
    setLayers,
    activeLayerId,
    setActiveLayerId,
    frontLayerColor,
    setFrontLayerColor,
    backLayerColor,
    setBackLayerColor,
    layerColorOverrides,
    setLayerColorOverrides,
  } = useEditorLayers()

  const {
    tool,
    setTool,
    clearDraft,
    setActiveTool,
    textDraftValue,
    textFontFamily,
    setTextFontFamily,
    textFontSizeMm,
    textTransformMode,
    textRadiusMm,
    textSweepDeg,
    showStitchSequenceLabels,
  } = useEditorTools()

  const {
    viewport,
    setViewport,
    workspaceRef,
  } = useEditorViewport({ isMobileLayout, showThreePreview })
  const {
    shellRef,
    showPeek,
    effectiveSecondaryPreviewMode,
    effectiveLayout,
    setActiveInspectorTab,
    handleBrowserResizeStart,
    handlePeekResizeStart,
    handleInspectorResizeStart,
    splitterWidth,
    toolRailWidth,
  } = useWorkbenchShellState({
    enabled: !isMobileLayout,
    secondaryPreviewMode,
  })

  const resolvedThemeMode: ResolvedThemeMode = themeMode === 'system' ? systemThemeMode : themeMode

  useWorkbenchRouteSync({
    enabled: !isMobileLayout,
    workspaceMode,
    setWorkspaceMode,
    setSecondaryPreviewMode,
    activeInspectorTab: effectiveLayout.activeInspectorTab,
    setActiveInspectorTab,
  })

  const {
    svgRef,
    fileInputRef,
    svgInputRef,
    tracingInputRef,
    backdropInputRef,
    templateImportInputRef,
    catalogImportInputRef,
    translationInputRef,
    fontInputRef,
    pasteCountRef,
    tracingObjectUrlsRef,
    panRef,
  } = useEditorScreenRefs()
  const [showPieceInspectorModal, setShowPieceInspectorModal] = useState(false)
  const {
    activeLayer,
    sketchGroupsById,
    activeSketchGroup,
    activeLineType,
    lineTypesById,
    shapesById,
    patternPiecesById,
    patternPieceByBoundaryShapeId,
    patternPieceChains,
    selectedShapeIdSet,
    shapeCountsByLineType,
    stitchHoleCountsByShape,
    selectedShapeCount,
    selectedStitchHoleCount,
    selectedStitchHole,
    selectedHardwareMarker,
    selectedTemplateEntry,
    canUndo,
    canRedo,
    assemblyShapes,
    visibleStitchHoles,
    visibleLayerIdSet,
    workspaceShapes,
    workspaceEditableShapes,
    workspaceLinkedShapes,
    workspaceStitchHoles,
    workspaceHardwareMarkers,
    seamGuides,
    annotationLabels,
    pieceGrainlineSegments,
    pieceNotchLines,
    piecePlacementGuides,
    lineTypeStylesById,
    printableShapes,
    activeExportRoleCount,
    layerColorsById,
    layerStackLevels,
    stackLegendEntries,
    displayLayerColorsById,
    fallbackLayerStroke,
    cutStrokeColor,
    stitchStrokeColor,
    foldStrokeColor,
    activeLineTypeStrokeColor,
    activeLineTypeDasharray,
    currentSnapshot,
    currentSnapshotSignature,
  } = useEditorDerivedState({
    templateRepository,
    selectedTemplateEntryId,
    themeMode: resolvedThemeMode,
  })

  // Detect closed outlines and open paths for canvas labels
  const outlineChains = useMemo<OutlineChain[]>(
    () => detectOutlines(workspaceEditableShapes, lineTypes),
    [workspaceEditableShapes, lineTypes],
  )

  const {
    applyEditorSnapshot,
    ensureActiveLayerWritable,
    ensureActiveLineTypeWritable,
    resetDocument,
  } = useEditorStateActions({
    activeLayer,
    activeSketchGroup,
    activeLineType,
    clearDraft,
    setDocumentName,
    setLayers,
    setActiveLayerId,
    setSketchGroups,
    setActiveSketchGroupId,
    setLineTypes,
    setActiveLineTypeId,
    setShapes,
    setFoldLines,
    setStitchHoles,
    setConstraints,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setHardwareMarkers,
    setSnapSettings,
    setShowAnnotations,
    setTracingOverlays,
    setBackdrops,
    setActiveBackdropId,
    setProjectMemo,
    setStitchAlwaysShapeIds,
    setStitchThreadColor,
    setThreePreviewSettings,
    setAvatars,
    setThreeTextureSource,
    setThreeTextureShapeIds,
    setShowCanvasRuler,
    setShowDimensions,
    setLayerColorOverrides,
    setFrontLayerColor,
    setBackLayerColor,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
    setShowPrintAreas,
    setStatus,
  })

  const { applyLoadedDocument } = useLoadedDocumentActions({
    clearDraft,
    setDocumentName,
    setLayers,
    setActiveLayerId,
    setSketchGroups,
    setActiveSketchGroupId,
    setLineTypes,
    setActiveLineTypeId,
    setShapes,
    setFoldLines,
    setStitchHoles,
    setConstraints,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setHardwareMarkers,
    setSnapSettings,
    setShowAnnotations,
    setTracingOverlays,
    setBackdrops,
    setActiveBackdropId,
    setProjectMemo,
    setStitchAlwaysShapeIds,
    setStitchThreadColor,
    setThreePreviewSettings,
    setAvatars,
    setThreeTextureSource,
    setThreeTextureShapeIds,
    setShowCanvasRuler,
    setShowDimensions,
    setDimensionLines,
    setPrintAreas,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
    setLayerColorOverrides,
    setTool,
    setShowPrintAreas,
    setStatus,
  })
  const { mergedCatalogRepository } = useEditorDocumentBootstrap({
    bundledCatalogRepository,
    catalogRepository,
    setSystemThemeMode,
    applyLoadedDocument,
  })

  const previewElement = useCombinedDraftAndSnapElement({
    activeLineTypeStrokeColor,
    activeLineTypeDasharray,
  })

  const { handleUndo, handleRedo } = useHistoryActions({
    currentSnapshot,
    applyEditorSnapshot,
  })

  const {
    handleCopySelection,
    handleDeleteSelection,
    handleCutSelection,
    handlePasteClipboard,
    handleDuplicateSelection,
    handleSelectAllShapes,
    handleGroupSelection,
    handleUngroupSelection,
    handleMoveSelectionByDistance,
    handleCopySelectionByDistance,
    handleRotateSelection,
    handleScaleSelection,
    handleMoveSelectionForward,
    handleMoveSelectionBackward,
    handleBringSelectionToFront,
    handleSendSelectionToBack,
  } = useSelectionActions({
    selectedShapeIdSet,
    selectedHardwareMarkerId,
    shapes,
    stitchHoles,
    patternPieces,
    pieceGrainlines,
    pieceLabels,
    piecePlacementLabels,
    seamAllowances,
    pieceNotches,
    activeLayerId: activeLayer?.id ?? null,
    clipboardPayload,
    pasteCountRef,
    setClipboardPayload,
    setShapes,
    setStitchHoles,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setConstraints,
    setSketchGroups,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
    setHardwareMarkers,
    setStatus,
  })

  const {
    handleAlignSelectionToEdge,
    handleFlipSelection,
    handleReverseSelectedPaths,
    handleSpecifyRotation,
    handleSpecifyScale,
    handleOpenSpecifyRotationModal,
    handleOpenSpecifyScaleModal,
    handleSetAsRotationCenter,
    handleClearRotationCenter,
    handleSetAsSnapPoint,
    handleClearSnapPoint,
    handleMakeSelectedLineHorizontal,
    handleMakeSelectedLineVertical,
  } = useTransformActions({
    shapes,
    selectedShapeIdSet,
    customRotationPivot,
    setShapes,
    setStitchHoles,
    setCustomRotationPivot,
    setCustomSnapPoint,
    setShowSpecifyRotationModal,
    setShowSpecifyScaleModal,
    setSpecifyScaleModalAxis,
    setStatus,
  })

  const selectedEditableShape =
    selectedShapeIds.length === 1 ? (shapesById[selectedShapeIds[0]] ?? null) : null
  const {
    buildCurrentDocFile,
    handleEnableStitchOnSelection,
    handleDisableStitchOnSelection,
    handleUpdateSelectedShapePoint,
    handleUpdateSelectedStitchHole,
    handleResetExportOptions,
    updateFoldLine,
  } = useEditorDocumentCommands({
    documentName,
    layers,
    activeLayerId,
    sketchGroups,
    activeSketchGroupId,
    lineTypes,
    activeLineTypeId,
    shapes,
    foldLines,
    stitchHoles,
    constraints,
    patternPieces,
    pieceGrainlines,
    pieceLabels,
    piecePlacementLabels,
    piecePlacements3d,
    seamConnections,
    seamAllowances,
    pieceNotches,
    hardwareMarkers,
    snapSettings,
    showAnnotations,
    tracingOverlays,
    backdrops,
    projectMemo,
    stitchAlwaysShapeIds,
    stitchThreadColor,
    threePreviewSettings,
    avatars,
    threeTextureSource,
    threeTextureShapeIds,
    showCanvasRuler,
    showDimensions,
    dimensionLines,
    printAreas,
    selectedShapeIdSet,
    selectedEditableShape,
    selectedStitchHole,
    setShapes,
    setStitchHoles,
    setStitchAlwaysShapeIds,
    setExportOnlySelectedShapes,
    setExportOnlyVisibleLineTypes,
    setExportRoleFilters,
    setExportForceSolidStrokes,
    setExportStitchHoleRenderMode,
    setExportStitchDotRadiusMm,
    setDxfFlipY,
    setDxfVersion,
    setFoldLines,
    setStatus,
  })
  const {
    handleSaveTemplateToRepository,
    handleDeleteTemplateFromRepository,
    handleLoadTemplateAsDocument,
    handleInsertTemplateIntoDocument,
    handleExportTemplateRepository,
    handleImportTemplateRepositoryFile,
    handleImportCatalogFile,
    handleDeleteCatalogShop,
  } = useTemplateActions({
    templateRepository,
    selectedTemplateEntry,
    selectedTemplateEntryId,
    selectedCatalogShopId,
    buildCurrentDocFile,
    applyLoadedDocument,
    layers,
    lineTypes,
    shapes,
    foldLines,
    stitchHoles,
    clearDraft,
    setTemplateRepository,
    setCatalogRepository,
    setSelectedTemplateEntryId,
    setSelectedCatalogShopId,
    setLayers,
    setLineTypes,
    setActiveLineTypeId,
    setShapes,
    setFoldLines,
    setStitchHoles,
    setSelectedShapeIds,
    setActiveLayerId,
    setStatus,
  })
  const {
    handleLoadAiBuilderDocument,
    handleInsertAiBuilderDocument,
  } = useAiBuilderActions({
    applyLoadedDocument,
    layers,
    lineTypes,
    shapes,
    foldLines,
    stitchHoles,
    clearDraft,
    setLayers,
    setLineTypes,
    setActiveLineTypeId,
    setShapes,
    setFoldLines,
    setStitchHoles,
    setSelectedShapeIds,
    setActiveLayerId,
    setStatus,
  })

  useEffect(() => {
    saveCatalogRepository(catalogRepository)
  }, [catalogRepository])

  const {
    handleUpdateTracingOverlay,
    handleDeleteTracingOverlay,
    handleSetPdfTracingPage,
    handleImportTracing,
  } = useTracingActions({
    setTracingOverlays,
    setActiveTracingOverlayId,
    setShowTracingModal,
    setStatus,
  })

  const {
    handleImportBackdrop,
    handleDeleteActiveBackdrop,
    handleUpdateBackdrop,
    handleBackdropUndo,
    handleBackdropRedo,
    activeBackdrop,
  } = useBackdropActions({
    backdrops,
    setBackdrops,
    activeBackdropId,
    setActiveBackdropId,
    setStatus,
  })

  useResponsiveLayout({
    setIsMobileLayout,
    setMobileViewMode,
    setShowMobileMenu,
    setMobileOptionsTab,
    setTool,
  })

  useEditorConsistencyEffects({
    layers,
    activeLayerId,
    setActiveLayerId,
    sketchGroups,
    setSketchGroups,
    setActiveSketchGroupId,
    lineTypes,
    activeLineTypeId,
    setLineTypes,
    setActiveLineTypeId,
    shapes,
    setSelectedShapeIds,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setConstraints,
    setStitchHoles,
    stitchHoles,
    setSelectedStitchHoleId,
    hardwareMarkers,
    setSelectedHardwareMarkerId,
    setHardwareMarkers,
    setLayerColorOverrides,
    tracingOverlays,
    setThreeTextureShapeIds,
    setActiveTracingOverlayId,
    tracingObjectUrlsRef,
    templateRepository,
    setSelectedTemplateEntryId,
    currentSnapshot,
    currentSnapshotSignature,
  })

  useEditorGlobalShortcuts({
    handleDeleteSelection,
    handleUndo,
    handleRedo,
    handleCopySelection,
    handleCutSelection,
    handlePasteClipboard,
    handleDuplicateSelection,
    handleSelectAllShapes,
    selectedShapeIdSet,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
    setShowCanvasRuler,
    setShowBezierOffsetLines,
    setShowGrid,
    setActiveTool,
    handleRotateSelection,
    setShapes,
    setStatus,
  })

  useEditorAutomationEffects({
    shapes,
    autoConstraintSettings,
    constraintSuggestions,
    setConstraintSuggestions,
  })

  const {
    handleZoomStep,
    handleResetView,
    handleFitView,
    handlePointerDown,
    handleShapePointerDown,
    handleShapeHandlePointerDown,
    handleStitchHolePointerDown,
    handleHardwarePointerDown,
    handlePointerMove,
    handlePointerUp,
    interactionPreview,
    runPrecisionCommand,
    toolHint,
  } = useEditorCanvasController({
    svgRef,
    panRef,
    viewport,
    activeLayerId,
    activeLineTypeId,
    activeSketchGroup,
    snapSettings,
    foldLines,
    displayShapes: workspaceShapes,
    snapShapes: workspaceShapes,
    customSnapPoint,
    reverseZoomDirection,
    incrementalSelection,
    lineToolConstraint,
    stitchTargetShapes: workspaceEditableShapes,
    visibleHardwareMarkers: workspaceHardwareMarkers,
    lineTypesById,
    shapesById,
    layers,
    stitchHoles,
    patternPieces,
    pieceNotches,
    seamConnections,
    hardwareMarkers,
    selectedShapeIds,
    selectedShapeIdSet,
    selectedStitchHoleId,
    selectedHardwareMarkerId,
    setViewport,
    setShapes,
    setStitchHoles,
    setSelectedStitchHoleId,
    setPieceNotches,
    setSeamConnections,
    setHardwareMarkers,
    setSelectedHardwareMarkerId,
    setFoldLines,
    setDimensionLines,
    setSelectedShapeIds,
    setActiveLineTypeId,
    setStatus,
    handleRotateSelection,
    handleScaleSelection,
    ensureActiveLayerWritable,
    ensureActiveLineTypeWritable,
  })
  const { handleExportSvg, handleExportDxf, handleExportPdf, handleExportLaserSvg } = useExportActions({
    shapes: assemblyShapes,
    foldLines,
    stitchHoles,
    lineTypes,
    lineTypesById,
    patternPiecesById,
    lineTypeStylesById,
    sketchGroupsById,
    selectedShapeIdSet,
    visibleLayerIdSet,
    showAnnotations,
    annotationLabels,
    pieceGrainlineSegments,
    pieceNotchLines,
    piecePlacementGuides,
    stitchAlwaysShapeIdSet: new Set(stitchAlwaysShapeIds),
    exportUnit: displayUnit,
  })

  const {
    handleSaveJson,
    handleSaveLcc,
    handleExportGarmentJson,
    handleLoadJson,
    handleImportSvg,
    handleLoadPreset,
    handleOpenInNewTab,
  } = useFileActions({
    buildCurrentDocFile,
    applyLoadedDocument,
    selectedPresetId,
    setSelectedPresetId,
    isMobileLayout,
    activeLayer,
    activeLineTypeId,
    activeSketchGroup,
    setShapes,
    setSelectedShapeIds,
    setStatus,
    setShowThreePreview,
    setMobileViewMode,
    setShowMobileMenu,
  })

  useAutoSave({
    enabled: autoSaveEnabled,
    buildDoc: () => buildCurrentDocFile(),
    setStatus,
  })

  // Leather-sim ↔ stitch-sim coupling: when leather-sim turns on, auto-open the
  // stitch simulator (source-app v2.5.6 behavior).
  useEffect(() => {
    if (leatherSimEnabled && !showStitchSimulatorModal) {
      setShowStitchSimulatorModal(true)
    }
  }, [leatherSimEnabled, showStitchSimulatorModal, setShowStitchSimulatorModal])

  const {
    handleAddLayer,
    handleRenameActiveLayer,
    handleToggleLayerVisibility,
    handleToggleLayerLock,
    handleMoveLayer,
    handleDeleteLayer,
    handleActivateLayerOfSelectedShape,
    handleDuplicateSelectedShapesOnBelowLayer,
    handleMoveSelectedShapesToLayerBelow,
    handleMoveSelectedShapesToAnotherLayer,
    handleHighlightShapesOnCurrentLayer,
    handleToggleLayerIgnored,
    handleToggleIndependentLayer,
  } = useLayerActions({
    activeLayer,
    layers,
    shapes,
    selectedShapeIdSet,
    setLayers,
    setActiveLayerId,
    setShapes,
    setSketchGroups,
    setHardwareMarkers,
    setConstraints,
    setSelectedShapeIds,
    setStatus,
  })

  const {
    handleToggleActiveLineTypeVisibility,
    handleShowAllLineTypes,
    handleIsolateActiveLineType,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    handleUpdateActiveLineTypeColor,
    handleSelectShapesByActiveLineType,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleLinePaletteSelectAll,
    handleLinePaletteUnselectLineType,
    handleLinePaletteUnselectOthers,
  } = useLineTypeActions({
    activeLineType,
    shapes,
    selectedShapeIdSet,
    setLineTypes,
    setShapes,
    setSelectedShapeIds,
    setStatus,
  })

  const {
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  } = useLayerColorActions({
    layerColorsById,
    setLayerColorOverrides,
    setFrontLayerColor,
    setBackLayerColor,
    setStatus,
  })

  const {
    handleCreateSketchGroupFromSelection,
    handleCreateLinkedSketchGroup,
    handleRenameActiveSketchGroup,
    handleToggleActiveSketchGroupVisibility,
    handleToggleActiveSketchGroupLock,
    handleSetActiveSketchLink,
    handleClearActiveSketchLink,
    handleClearActiveSketchGroup,
    handleDeleteActiveSketchGroup,
    handleDuplicateActiveSketchGroup,
    handleSetActiveLayerAnnotation,
    handleSetActiveSketchAnnotation,
  } = useSketchGroupActions({
    activeLayer,
    activeSketchGroup,
    selectedShapeIdSet,
    sketchGroups,
    shapes,
    stitchHoles,
    patternPieces,
    pieceGrainlines,
    pieceLabels,
    piecePlacementLabels,
    seamAllowances,
    pieceNotches,
    hardwareMarkers,
    setSketchGroups,
    setShapes,
    setStitchHoles,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setSeamAllowances,
    setPieceNotches,
    setHardwareMarkers,
    setSelectedShapeIds,
    setActiveSketchGroupId,
    setLayers,
    setStatus,
  })
  const [stitchSimulatorSettings, setStitchSimulatorSettings] = useState<StitchSimulatorSettings>(() =>
    loadStitchSimulatorSettings(),
  )
  const [boxStitchHelperSettings, setBoxStitchHelperSettings] = useState<BoxStitchHelperSettings>(() =>
    loadBoxStitchHelperSettings(),
  )
  const {
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleClearAllSeamAllowances,
    handleToggleConstraintEnabled,
    handleDeleteConstraint,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleCreateOffsetGeometryFromSelection,
    preloadBoxStitchGeneration,
    applyBoxStitchToSelection,
  } = useConstraintActions({
    activeLayer,
    activeLayerId: activeLayer?.id ?? null,
    activeLineTypeId,
    stitchLineTypeId: STITCH_LINE_TYPE_ID,
    layers,
    shapes,
    selectedShapeIds,
    selectedShapeIdSet,
    constraints,
    patternPieces,
    seamAllowances,
    snapSettings,
    boxStitchHelperSettings,
    setShapes,
    setStitchHoles,
    setSelectedShapeIds,
    setConstraints,
    setSeamAllowances,
  })

  const {
    selectedShapes,
    selectionBounds,
    selectedPatternPiece,
    selectedPieceGrainline,
    selectedPieceLabel,
    selectedPatternLabel,
    selectedPieceSeamAllowance,
    selectedPieceSeamConnections,
    selectedPieceNotches,
    selectedPiecePlacementLabels,
    selectedPieceInternalShapeIdSet,
    selectedPatternPieceEdgeCount,
    pieceEdgeLabels,
    selectedPieceAvailableInternalShapes,
  } = usePatternPieceSelection({
    isPieceInspectorOpen: showPieceInspectorModal,
    tool,
    selectedShapeIds,
    shapesById,
    shapes,
    patternPieces,
    patternPiecesById,
    patternPieceByBoundaryShapeId,
    patternPieceChains,
    pieceGrainlines,
    pieceLabels,
    seamAllowances,
    seamConnections,
    pieceNotches,
    piecePlacementLabels,
    visibleLayerIdSet,
  })

  const {
    ensurePatternPieceSupportRecords,
    openSelectedPatternPieceInspector,
    handleCreatePatternPieceFromSelection,
    handleUpdateSelectedPatternPiece,
    handleToggleSelectedPieceInternalShape,
    updateSelectedLabel,
    handleUpdateSelectedPieceGrainline,
    handleUpdateSelectedPieceSeamAllowance,
    handleUpdateSelectedPieceSeamConnection,
    handleUpdateSelectedPieceNotch,
    handleAddSelectedPiecePlacementLabel,
    handleUpdateSelectedPiecePlacementLabel,
    handleDeleteSelectedPiecePlacementLabel,
  } = usePatternPieceCommands({
    isMobileLayout,
    selectedShapeIds,
    shapesById,
    patternPieces,
    patternPieceByBoundaryShapeId,
    patternPieceChainsByShapeId: patternPieceChains.byShapeId,
    selectedPatternPiece,
    selectedPatternPieceEdgeCount,
    pieceGrainlines,
    pieceLabels,
    seamAllowances,
    setPatternPieces,
    setPieceGrainlines,
    setPieceLabels,
    setSeamAllowances,
    setSeamConnections,
    setPieceNotches,
    setPiecePlacementLabels,
    setShowPieceInspectorModal,
    setActiveInspectorTab,
    setStatus,
  })

  const { handleDeleteSelectedHardwareMarker, handleUpdateSelectedHardwareMarker } = useHardwareMarkerActions({
    selectedHardwareMarker,
    setHardwareMarkers,
    setSelectedHardwareMarkerId,
    setStatus,
  })
  const {
    handleCountStitchHolesOnSelectedShapes,
    handleDeleteStitchHolesOnSelectedShapes,
    handleClearAllStitchHoles,
    handleAutoPlacePreferredPitchStitchHoles,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleAutoPlaceEvenlySpacedStitchHoles,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleFixStitchHoleOrderFromSelected,
  } = useStitchActions({
    selectedShapeIdSet,
    selectedStitchHoleCount,
    stitchHoles,
    setStitchHoles,
    setSelectedStitchHoleId,
    shapes,
    lineTypesById,
    selectedStitchHole,
    shapesById,
    layers,
    stitchHoleCountsByShape,
  })

  const {
    handleConvertArcToBezier,
    handleMakeBezierCpFlat,
    handleMakeBezierCpSameLength,
    handleMakeBezierCpSymmetric,
    handleExtendOrTrimLines,
    handleMirrorShapes,
    handleToggleBezierOffsetLines,
    handleResizeShapes,
    handleCenterLineBetweenSelection,
    handleEditSelectedLineAngle,
    handleDeleteDuplicates,
    handleSplitIntoN,
    handleDrawBoundaryAroundSelection,
    handleFilletSelectedCorner,
    handleDistanceMarkSelectedPath,
    handleConvertSelectionToPath,
    handleNotchSelectedShape,
  } = useGeometryEditingActions({
    shapes,
    setShapes,
    selectedShapeIdSet,
    setSelectedShapeIds,
    activeLayerId,
    activeLineTypeId,
    setStatus,
    showBezierOffsetLines,
    setShowBezierOffsetLines,
  })
  const {
    stitchSimulatorResult,
    handleMarkSelectedStitchHoleAsEnd,
    handleClearSelectedStitchHoleEnd,
    handleExtractSelectedBoxStitchSources,
    handleClearSelectedBoxStitchSources,
    handleApplyTextDefaultsToSelection,
    handleGenerateBoxStitch,
    handleOpenBoxStitchHelperModal,
    handleApplyBoxStitchHelper,
    handleGenerateMandalaRadial,
    handleGenerateSpiral,
    handleGenerateGoldenGuides,
    handleGenerateWhiteSilverGuides,
    handleGenerateWizardPattern,
    handleGenerateLetterStamp,
  } = useEditorCreationController({
    shapes,
    setShapes,
    stitchHoles,
    setStitchHoles,
    selectedShapeIdSet,
    selectedStitchHole,
    activeLayerId,
    activeLineTypeId,
    textDraftValue,
    textFontFamily,
    textFontSizeMm,
    textTransformMode,
    textRadiusMm,
    textSweepDeg,
    showStitchSimulatorModal,
    stitchSimulatorSettings,
    setStitchSimulatorSettings,
    setBoxStitchHelperSettings,
    setShowBoxStitchModal,
    setShowBoxStitchHelperModal,
    setShowMandalaModal,
    setShowWizardModal,
    setShowLetterStampModal,
    setStatus,
    preloadBoxStitchGeneration,
    applyBoxStitchToSelection,
  })

  const { handleRunMobileLayerAction, handleRunMobileFileAction } = useMobileActions({
    mobileLayerAction,
    mobileFileAction,
    fileInputRef,
    svgInputRef,
    tracingInputRef,
    handleAddLayer,
    handleRenameActiveLayer,
    handleToggleLayerVisibility,
    handleToggleLayerLock,
    handleMoveLayer,
    handleDeleteLayer,
    handleSaveJson,
    handleSaveLcc,
    handleLoadPreset,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    handleUndo,
    handleRedo,
    handleCopySelection,
    handlePasteClipboard,
    handleDeleteSelection,
    resetDocument,
    setShowLayerColorModal,
    setShowExportOptionsModal,
    setShowTemplateRepositoryModal,
    setShowPatternToolsModal,
    setShowPrintPreviewModal,
    setShowThreePreview,
  })

  const { handleSetThemeMode } = useThemeActions({
    setThemeMode,
    setStatus,
  })
  const {
    handleBooleanOp,
    handleClipperOffset,
    handleTextToPath,
    handleFontInputChange,
  } = useEditorAssetCommands({
    loadedFontUrl,
    shapes,
    selectedShapeIds,
    selectedShapeIdSet,
    activeLayerId: activeLayer?.id ?? '',
    activeLineTypeId,
    setShapes,
    setSelectedShapeIds,
    setLoadedFontUrl,
    setStatus,
    fontInputRef,
  })

  const {
    printOutputPlan,
    handleOpenPrintTiles,
  } = usePrintPreviewState({
    lineTypes,
    activeLineTypeId,
    activeLayerId,
    showAnnotations,
    selectedShapeIdSet,
    patternPiecesById,
    annotationLabels,
    pieceGrainlineSegments,
    pieceNotchLines,
    piecePlacementGuides,
    printableShapes,
    foldLines,
    lineTypesById,
  })

  const {
    workspaceClassName,
    topbarClassName,
    hideCanvasPane,
    hidePreviewPane,
    showToolSection,
    showZoomSection,
    showEditSection,
    showLineTypeSection,
    showStitchSection,
    showLayerSection,
    showFileSection,
    showLayerLegend,
  } = useEditorLayoutFlags({
    isMobileLayout,
    mobileViewMode,
    showThreePreview,
    showMobileMenu,
    mobileOptionsTab,
    desktopRibbonTab,
  })
  const topbarProps = useEditorTopbarViewModel({
    tracingInputRef,
    translationInputRef,
    shapes,
    stitchHoles,
    foldLines,
    selectedShapeIds,
    selectedShapeIdSet,
    setShapes,
    setStitchHoles,
    setFoldLines,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setStatus,
    resetDocument,
    setShowFontListModal,
    setShowWizardModal,
    setShowBackdropModal,
    setShowOptionsModal,
    setShowLengthAdjustModal,
    handleEditSelectedLineAngle,
    handleDeleteDuplicates,
    handleSplitIntoN,
    handleFilletSelectedCorner,
    handleDistanceMarkSelectedPath,
    handleConvertSelectionToPath,
    handleNotchSelectedShape,
    topbarClassName,
    selectedShapeCount,
    selectedStitchHoleCount,
    showToolSection,
    handleLoadPreset,
    handleSetThemeMode,
    showZoomSection,
    showEditSection,
    canUndo,
    canRedo,
    handleUndo,
    handleRedo,
    handleCopySelection,
    handleCutSelection,
    handlePasteClipboard,
    canPaste: true,
    handleSelectAllShapes,
    handleDuplicateSelection,
    handleDeleteSelection,
    handleGroupSelection,
    handleUngroupSelection,
    handleMoveSelectionByDistance,
    handleCopySelectionByDistance,
    handleRotateSelection,
    handleScaleSelection,
    handleAlignSelectionToEdge,
    handleFlipSelection,
    handleReverseSelectedPaths,
    handleOpenSpecifyRotationModal,
    handleOpenSpecifyScaleModal,
    handleSetAsRotationCenter,
    handleClearRotationCenter,
    handleSetAsSnapPoint,
    handleClearSnapPoint,
    handleMakeSelectedLineHorizontal,
    handleMakeSelectedLineVertical,
    hasCustomRotationPivot: customRotationPivot !== null,
    hasCustomSnapPoint: customSnapPoint !== null,
    handleCenterLineBetweenSelection,
    handleDrawBoundaryAroundSelection,
    handleActivateLayerOfSelectedShape,
    handleDuplicateSelectedShapesOnBelowLayer,
    handleMoveSelectedShapesToLayerBelow,
    handleMoveSelectedShapesToAnotherLayer,
    handleHighlightShapesOnCurrentLayer,
    handleToggleLayerIgnored,
    handleToggleIndependentLayer,
    handleEnableStitchOnSelection,
    handleDisableStitchOnSelection,
    handleMoveSelectionBackward,
    handleMoveSelectionForward,
    handleSendSelectionToBack,
    handleBringSelectionToFront,
    showLineTypeSection,
    handleToggleActiveLineTypeVisibility,
    showStitchSection,
    handleAutoPlacePreferredPitchStitchHoles,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleAutoPlaceEvenlySpacedStitchHoles,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleFixStitchHoleOrderFromSelected,
    handleCountStitchHolesOnSelectedShapes,
    handleDeleteStitchHolesOnSelectedShapes,
    handleClearAllStitchHoles,
    stitchHolesLength: stitchHoles.length,
    hasSelectedStitchHole: selectedStitchHole !== null,
    showLayerSection,
    activeLayer,
    layerStackLevels,
    handleRunMobileLayerAction,
    handleAddLayer,
    handleRenameActiveLayer,
    handleToggleLayerVisibility,
    handleToggleLayerLock,
    handleMoveLayer,
    handleDeleteLayer,
    setShowLayerColorModal,
    showFileSection,
    handleRunMobileFileAction,
    handleSaveJson,
    fileInputRef,
    svgInputRef,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    handleExportLaserSvg,
    handleOpenInNewTab,
  })

  const overlayModalStackParams = {
    shapeCountsByLineType,
    selectedShapeCount,
    handleShowAllLineTypes,
    handleIsolateActiveLineType,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    handleUpdateActiveLineTypeColor,
    handleSelectShapesByActiveLineType,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleLinePaletteSelectAllVisible: () => handleLinePaletteSelectAll(lineTypes),
    handleLinePaletteUnselectActive: () => {
      if (activeLineType) handleLinePaletteUnselectLineType(activeLineType.id)
    },
    handleLinePaletteUnselectOtherThanActive: () => {
      if (activeLineType) handleLinePaletteUnselectOthers(activeLineType.id)
    },
    layerColorsById,
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
    handleSaveJson,
    handleExportGarmentJson,
    handleSaveLcc,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    handleExportLaserSvg,
    activeExportRoleCount,
    handleResetExportOptions,
    templateRepository,
    catalogRepository: mergedCatalogRepository,
    selectedTemplateEntryId,
    selectedTemplateEntry,
    selectedCatalogShopId,
    setSelectedTemplateEntryId,
    setSelectedCatalogShopId,
    handleSaveTemplateToRepository,
    handleExportTemplateRepository,
    templateImportInputRef,
    catalogImportInputRef,
    handleLoadPreset,
    handleLoadTemplateAsDocument,
    handleInsertTemplateIntoDocument,
    handleDeleteTemplateFromRepository,
    handleDeleteCatalogShop,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    activeLayer,
    handleCreateSketchGroupFromSelection,
    handleCreateLinkedSketchGroup,
    handleDuplicateActiveSketchGroup,
    handleRenameActiveSketchGroup,
    handleToggleActiveSketchGroupVisibility,
    handleToggleActiveSketchGroupLock,
    handleSetActiveSketchLink,
    handleClearActiveSketchLink,
    handleClearActiveSketchGroup,
    handleDeleteActiveSketchGroup,
    handleSetActiveLayerAnnotation,
    handleSetActiveSketchAnnotation,
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleToggleConstraintEnabled,
    handleDeleteConstraint,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleClearAllSeamAllowances,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleCreateOffsetGeometryFromSelection,
    handleCreateBoxStitchFromSelection: handleOpenBoxStitchHelperModal,
    selectedEditableShape,
    handleUpdateSelectedShapePoint,
    handleApplyTextDefaultsToSelection,
    selectedHardwareMarker,
    handleUpdateSelectedHardwareMarker,
    handleDeleteSelectedHardwareMarker,
    handleBooleanOp,
    handleClipperOffset,
    handleTextToPath,
    handleOpenNesting: () => setShowNestingModal(true),
    tracingInputRef,
    handleDeleteTracingOverlay,
    handleUpdateTracingOverlay,
    handleSetPdfTracingPage,
    printPlan: printOutputPlan,
    handleFitView,
    handleOpenPrintTiles,
    handleLoadAiBuilderDocument,
    handleInsertAiBuilderDocument,
  }
  const previewPaneProps = useEditorPreviewPaneProps({
    hidePreviewPane,
    shapes: sketchWorkspaceMode === 'assembly' ? assemblyShapes : workspaceShapes,
    stitchHoles: sketchWorkspaceMode === 'assembly' ? visibleStitchHoles : workspaceStitchHoles,
    themeMode: resolvedThemeMode,
    activeLayer,
    layerStackLevels,
    layerColorsById,
    onClearDraft: clearDraft,
    onAddLayer: handleAddLayer,
    onRenameActiveLayer: handleRenameActiveLayer,
    onMoveLayerUp: () => handleMoveLayer(-1),
    onMoveLayerDown: () => handleMoveLayer(1),
    onDeleteLayer: handleDeleteLayer,
    onOpenLayerColorModal: () => setShowLayerColorModal(true),
  })
  const statusBarProps = useEditorStatusBarProps({
    toolLabel: toolLabel(tool),
    zoomPercent: Math.round(viewport.scale * 100),
    visibleShapeCount: workspaceShapes.length,
    layerCount: layers.length,
    templateCount: templateRepository.length,
  })
  const workbenchController = useEditorWorkbenchController({
    documentName,
    patternPieces,
    patternPiecesById,
    pieceLabels,
    seamAllowances,
    pieceNotches,
    piecePlacementLabels,
    seamConnections,
    layers,
    activeLayerId,
    sketchGroups,
    activeSketchGroupId,
    tracingOverlays,
    activeTracingOverlayId,
    avatars,
    threeTextureSource,
    selectedShapes,
    selectedPatternPiece,
    selectedStitchHole,
    selectedHardwareMarker,
    selectedShapeCount,
    selectedShapeIdSet,
    canUndo,
    canRedo,
    workbenchRibbonTab,
    setActiveInspectorTab,
    isMobileLayout,
    workspaceMode,
    handleSaveJson,
    handleUndo,
    handleRedo,
    setShowHelpModal,
    handleFitView,
    handleResetView,
    setShowCanvasRuler,
    setShowDimensions,
    handleLoadPreset,
    setShowAnnotations,
    handleCopySelection,
    handlePasteClipboard,
    handleDeleteSelection,
    handleMoveSelectionByDistance,
    handleRotateSelection,
    handleScaleSelection,
    handleCreatePatternPieceFromSelection,
    openSelectedPatternPieceInspector,
    handleApplySeamAllowanceToSelection,
    setShowNestingModal,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleCountStitchHolesOnSelectedShapes,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleClearAllStitchHoles,
    fileInputRef,
    svgInputRef,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    setShowPrintPreviewModal,
    setShowTemplateRepositoryModal,
    setShowTracingModal,
    setShowAiBuilderModal,
    handleConvertArcToBezier,
    handleExtendOrTrimLines,
    handleMirrorShapes,
    handleMakeBezierCpSymmetric,
    handleToggleBezierOffsetLines,
    setShowChangeShapeSizeModal,
    setShowStitchSimulatorModal,
    setShowBoxStitchHelperModal,
    setShowBoxStitchModal,
    setShowWizardModal,
    setShowMandalaModal,
    setShowLetterStampModal,
    ensurePatternPieceSupportRecords,
    setSelectedShapeIds,
    setActiveLayerId,
    clearDraft,
    setActiveSketchGroupId,
    setActiveTracingOverlayId,
    setLayers,
    setTracingOverlays,
    setSecondaryPreviewMode,
    setWorkspaceMode,
  })
  const shouldLoadThreeWorkbench = workspaceMode === '3d'
  const selectionInspectorProps = buildSelectionInspectorProps({
    context: workbenchController.selectionContext,
    selectedShapeCount,
    selectedEditableShape,
    selectedStitchHole,
    selectedHardwareMarker,
    shapeCount: shapes.length,
    layerCount: layers.length,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleCreateOffsetGeometryFromSelection,
    handleOpenBoxStitchHelperModal,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleCreatePatternPieceFromSelection,
    openSelectedPatternPieceInspector,
    canOpenPieceTab: selectedPatternPiece !== null,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleApplyTextDefaultsToSelection,
    handleExtractSelectedBoxStitchSources,
    handleClearSelectedBoxStitchSources,
    handleUpdateSelectedShapePoint,
    handleUpdateSelectedStitchHole,
    handleMarkSelectedStitchHoleAsEnd,
    handleClearSelectedStitchHoleEnd,
    handleUpdateSelectedHardwareMarker,
    handleDeleteSelectedHardwareMarker,
  })

  const pieceInspectorContentProps = buildPieceInspectorContentProps({
    selectedPatternPiece,
    selectedPieceGrainline,
    selectedPieceLabel,
    selectedPatternLabel,
    selectedPieceSeamAllowance,
    selectedPieceSeamConnections,
    selectedPieceNotches,
    selectedPiecePlacementLabels,
    selectedPatternPieceEdgeCount,
    selectedPieceAvailableInternalShapes,
    selectedPieceInternalShapeIdSet,
    handleUpdateSelectedPatternPiece,
    handleToggleSelectedPieceInternalShape,
    handleUpdateSelectedPieceGrainline,
    updateSelectedLabel,
    handleUpdateSelectedPieceSeamAllowance,
    handleUpdateSelectedPieceSeamConnection,
    setSeamConnections,
    handleUpdateSelectedPieceNotch,
    setPieceNotches,
    handleAddSelectedPiecePlacementLabel,
    handleUpdateSelectedPiecePlacementLabel,
    handleDeleteSelectedPiecePlacementLabel,
  })

  const documentInspectorProps = buildDocumentInspectorProps({
    displayUnit,
    setDisplayUnit,
    gridSpacing,
    setGridSpacing,
    showCanvasRuler,
    setShowCanvasRuler,
    showDimensions,
    setShowDimensions,
    showAnnotations,
    setShowAnnotations,
    sketchWorkspaceMode,
    setSketchWorkspaceMode,
    themeMode,
    handleSetThemeMode,
    snapSettings,
    setSnapSettings,
    projectMemo,
    setProjectMemo,
    activeLineType,
    lineTypes,
    shapeCountsByLineType,
    selectedShapeCount,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleIsolateActiveLineType,
    handleSelectShapesByActiveLineType,
    setActiveLineTypeId,
    handleShowAllLineTypes,
    setLineTypes,
    handleUpdateActiveLineTypeColor,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    layers,
    layerColorsById,
    layerColorOverrides,
    frontLayerColor,
    backLayerColor,
    setFrontLayerColor,
    setBackLayerColor,
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  })

  const workbenchProps = buildWorkbenchProps({
    controller: workbenchController,
    shellRef,
    workspaceMode,
    secondaryPreviewMode: effectiveSecondaryPreviewMode,
    showPeek,
    browserWidth: effectiveLayout.browserWidth,
    inspectorWidth: effectiveLayout.inspectorWidth,
    peekWidth: effectiveLayout.peekWidth,
    splitterWidth,
    toolRailWidth,
    activeRibbonTab: workbenchRibbonTab,
    themeMode,
    onSetRibbonTab: setWorkbenchRibbonTab,
    onSetThemeMode: handleSetThemeMode,
    setLayers,
    tool,
    onSetActiveTool: setActiveTool,
    activeInspectorTab: effectiveLayout.activeInspectorTab,
    onSetActiveInspectorTab: setActiveInspectorTab,
    onStartBrowserResize: handleBrowserResizeStart,
    onStartPeekResize: handlePeekResizeStart,
    onStartInspectorResize: handleInspectorResizeStart,
    zoomScale: viewport.scale,
    displayUnit,
    activeLayer,
    activeLineType,
    onTogglePrecision: () => setShowPrecisionModal((previous) => !previous),
  })
  const workbenchThreeWorkspaceProps = buildWorkbenchThreeWorkspaceProps({
    workspaceMode,
    shapes: sketchWorkspaceMode === 'assembly' ? assemblyShapes : workspaceShapes,
    selectedShapeIds,
    stitchHoles: sketchWorkspaceMode === 'assembly' ? visibleStitchHoles : workspaceStitchHoles,
    stitchThreadColor,
    onSetStitchThreadColor: setStitchThreadColor,
    patternPieces,
    piecePlacements3d,
    seamConnections,
    threePreviewSettings,
    avatars,
    onSetPiecePlacements3d: setPiecePlacements3d,
    onSetThreePreviewSettings: setThreePreviewSettings,
    onSetAvatars: setAvatars,
    threeTextureSource,
    onSetThreeTextureSource: setThreeTextureSource,
    threeTextureShapeIds,
    onSetThreeTextureShapeIds: setThreeTextureShapeIds,
    foldLines,
    layers,
    lineTypes,
    themeMode: resolvedThemeMode,
    onUpdateFoldLine: updateFoldLine,
  })
  const { mobileShell, desktopShell } = useEditorWorkbenchProps({
    workspaceRef,
    workspaceClassName,
    topbarProps,
    hideCanvasPane,
    previewPaneProps,
    statusBarProps,
    toolHint,
    runPrecisionCommand,
    showPrecisionModal,
    setShowPrecisionModal,
    workbenchProps,
    selectionInspectorProps,
    pieceInspectorContentProps,
    documentInspectorProps,
    workbenchThreeWorkspaceProps,
    onOpenThreeWorkspace: () => workbenchController.handleSetWorkbenchMode('3d'),
    shouldLoadThreeWorkbench,
    canvasPaneParams: buildCanvasPaneParams({
      svgRef,
      onPointerDown: handlePointerDown,
      onPointerMove: handlePointerMove,
      onPointerUp: handlePointerUp,
      showGrid,
      gridBackgroundMode,
      setTracingOverlays,
      setBackdrops,
      setActiveBackdropId,
      shapes,
      selectedStitchHole,
      handleBringSelectionToFront,
      handleSendSelectionToBack,
      handleDuplicateSelection,
      handleConvertSelectionToPath,
      handleDeleteSelection,
      handleMakeBezierCpFlat,
      handleMakeBezierCpSameLength,
      handleMakeBezierCpSymmetric,
      handleClearSelectedStitchHoleEnd,
      handleMarkSelectedStitchHoleAsEnd,
      viewport,
      displayUnit,
      gridSpacing,
      showCanvasRuler,
      showDimensions,
      handleZoomStep,
      onFitView: handleFitView,
      onResetView: handleResetView,
      tracingOverlays,
      backdrops,
      activeBackdropId,
      showPrintAreas,
      dimensionLines,
      printPlan: printOutputPlan,
      seamGuides,
      pieceEdgeLabels,
      showAnnotations,
      pieceGrainlineSegments,
      pieceNotchLines,
      piecePlacementGuides,
      visibleShapes: workspaceEditableShapes,
      linkedShapes: workspaceLinkedShapes,
      sketchWorkspaceMode,
      lineTypes,
      lineTypesById,
      selectedShapeIdSet,
      stitchStrokeColor,
      foldStrokeColor,
      cutStrokeColor,
      displayLayerColorsById,
      onShapePointerDown: handleShapePointerDown,
      onShapeHandlePointerDown: handleShapeHandlePointerDown,
      tool,
      visibleStitchHoles: workspaceStitchHoles,
      selectedStitchHoleId,
      showStitchSequenceLabels,
      onStitchHolePointerDown: handleStitchHolePointerDown,
      stitchSimulatorResult,
      stitchSimulatorSettings,
      visibleHardwareMarkers: workspaceHardwareMarkers,
      selectedHardwareMarkerId,
      onHardwarePointerDown: handleHardwarePointerDown,
      foldLines,
      annotationLabels,
      constraintSuggestions,
      previewElement,
      interactionPreview,
      showLayerLegend,
      legendMode,
      onSetLegendMode: setLegendMode,
      layers,
      layerColorsById,
      fallbackLayerStroke,
      stackLegendEntries,
      outlineChains,
    }),
  })

  const overlay = useEditorOverlayViewModel({
    modalStack: overlayModalStackParams,
    overlay: {
    showStitchSimulatorModal,
    setShowStitchSimulatorModal,
    stitchSimulatorSettings,
    setStitchSimulatorSettings,
    stitchSimulatorResult,
    stitchHoles,
    selectedStitchHole,
    showBoxStitchHelperModal,
    setShowBoxStitchHelperModal,
    boxStitchHelperSettings,
    handleApplyBoxStitchHelper,
    selectedShapeCount,
    showBoxStitchModal,
    setShowBoxStitchModal,
    handleGenerateBoxStitch,
    activeLayerId,
    activeLineTypeId,
    showMandalaModal,
    setShowMandalaModal,
    handleGenerateMandalaRadial,
    handleGenerateSpiral,
    handleGenerateGoldenGuides,
    handleGenerateWhiteSilverGuides,
    showWizardModal,
    setShowWizardModal,
    handleGenerateWizardPattern,
    showBackdropModal,
    setShowBackdropModal,
    backdrops,
    activeBackdrop,
    onSelectBackdrop: setActiveBackdropId,
    onImportBackdrop: () => backdropInputRef.current?.click(),
    onDeleteActiveBackdrop: handleDeleteActiveBackdrop,
    onUpdateBackdrop: handleUpdateBackdrop,
    onBackdropUndo: handleBackdropUndo,
    onBackdropRedo: handleBackdropRedo,
    backdropFileInputRef: backdropInputRef,
    onBackdropFileChange: handleImportBackdrop,
    showLetterStampModal,
    setShowLetterStampModal,
    handleGenerateLetterStamp,
    showChangeShapeSizeModal,
    setShowChangeShapeSizeModal,
    handleResizeShapes,
    selectionBounds,
    showSpecifyRotationModal,
    setShowSpecifyRotationModal,
    handleSpecifyRotation,
    showSpecifyScaleModal,
    setShowSpecifyScaleModal,
    specifyScaleModalAxis,
    handleSpecifyScale,
    showFontListModal,
    setShowFontListModal,
    fontList,
    setFontList,
    setTextFontFamily,
    showOptionsModal,
    setShowOptionsModal,
    autoSaveEnabled,
    reverseZoomDirection,
    incrementalSelection,
    mentoriWithoutCtrl,
    exportIncludeText,
    exportIncludeTemplateMetadata,
    setAutoSaveEnabled,
    setReverseZoomDirection,
    setIncrementalSelection,
    setMentoriWithoutCtrl,
    setExportIncludeText,
    setExportIncludeTemplateMetadata,
    leatherSimTextureRotationDeg,
    lineToolConstraint,
    setLineToolConstraint,
    gridBackgroundMode,
    setGridBackgroundMode,
    showLengthAdjustModal,
    setShowLengthAdjustModal,
    shapes,
    selectedShapeIdSet,
    setShapes,
    showProjectMemoModal,
    setShowProjectMemoModal,
    projectMemo,
    setProjectMemo,
    isMobileLayout,
    showPieceInspectorModal,
    setShowPieceInspectorModal,
    pieceInspectorContentProps,
    showNestingModal,
    setShowNestingModal,
    patternPieces,
    pieceGrainlines,
    patternPieceChainsByShapeId: patternPieceChains.byShapeId,
    fileInputRef,
    svgInputRef,
    tracingInputRef,
    templateImportInputRef,
    catalogImportInputRef,
    translationInputRef,
    handleLoadJson,
    handleImportSvg,
    handleImportTracing,
    handleImportTemplateRepositoryFile,
    handleImportCatalogFile,
    setTranslationMap,
    fontInputRef,
    onFontInputChange: handleFontInputChange,
    setStatus,
    },
  })

  return {
    layout: {
      isMobileLayout,
      resolvedThemeMode,
      shouldLoadThreeWorkbench,
    },
    mobileShell,
    desktopShell,
    overlay,
  }
}
