import type { Dispatch, SetStateAction } from 'react'
import type { UseEditorScreenShellsParams } from '../../editorScreenShellTypes'
import type { BoxStitchHelperSettings } from '../../ops/box-stitch-settings'
import type { StitchSimulatorSettings } from '../../ops/stitch-simulator-ops'
import type { useAiBuilderActions } from '../../hooks/useAiBuilderActions'
import type { useBackdropActions } from '../../hooks/useBackdropActions'
import type { useEditorAssetCommands } from '../../useEditorAssetCommands'
import type { useTemplateActions } from '../../hooks/useTemplateActions'
import type { useTracingActions } from '../../hooks/useTracingActions'
import {
  useEditorOverlayViewModel,
  type UseEditorOverlayViewModelParams,
} from './useEditorOverlayViewModel'

type OverlayPropsParams = UseEditorOverlayViewModelParams['overlay']

type UseEditorScreenOverlayParams = UseEditorScreenShellsParams & {
  mergedCatalogRepository: UseEditorScreenShellsParams['repositoryState']['catalogRepository']
  stitchSimulatorSettings: StitchSimulatorSettings
  setStitchSimulatorSettings: Dispatch<SetStateAction<StitchSimulatorSettings>>
  boxStitchHelperSettings: BoxStitchHelperSettings
  setBoxStitchHelperSettings: Dispatch<SetStateAction<BoxStitchHelperSettings>>
  showPieceInspectorModal: boolean
  setShowPieceInspectorModal: Dispatch<SetStateAction<boolean>>
  pieceInspectorContentProps: OverlayPropsParams['pieceInspectorContentProps']
  templateActions: ReturnType<typeof useTemplateActions>
  aiBuilderActions: ReturnType<typeof useAiBuilderActions>
  tracingActions: ReturnType<typeof useTracingActions>
  backdropActions: ReturnType<typeof useBackdropActions>
  assetCommands: ReturnType<typeof useEditorAssetCommands>
}

export function useEditorScreenOverlay({
  documentState,
  uiState,
  panelState,
  repositoryState,
  layerState,
  toolState,
  screenRefs,
  derivedState,
  canvasController,
  patternPieceSelection,
  printPreviewState,
  selectedEditableShape,
  actions,
  mergedCatalogRepository,
  stitchSimulatorSettings,
  setStitchSimulatorSettings,
  boxStitchHelperSettings,
  setBoxStitchHelperSettings,
  showPieceInspectorModal,
  setShowPieceInspectorModal,
  pieceInspectorContentProps,
  templateActions,
  aiBuilderActions,
  tracingActions,
  backdropActions,
  assetCommands,
}: UseEditorScreenOverlayParams) {
  const {
    lineTypes,
    activeLineTypeId,
    shapes,
    setShapes,
    stitchHoles,
    backdrops,
    setActiveBackdropId,
    projectMemo,
    setProjectMemo,
    patternPieces,
    pieceGrainlines,
    dimensionLines,
    setDimensionLines,
  } = documentState
  const {
    setStatus,
    isMobileLayout,
    showProjectMemoModal,
    setShowProjectMemoModal,
    showNestingModal,
    setShowNestingModal,
    showStitchSimulatorModal,
    setShowStitchSimulatorModal,
    showBoxStitchHelperModal,
    setShowBoxStitchHelperModal,
    showBoxStitchModal,
    setShowBoxStitchModal,
    showMandalaModal,
    setShowMandalaModal,
    showWizardModal,
    setShowWizardModal,
    showBackdropModal,
    setShowBackdropModal,
    showLetterStampModal,
    setShowLetterStampModal,
    showChangeShapeSizeModal,
    setShowChangeShapeSizeModal,
    showMoveCopyDistanceModal,
    setShowMoveCopyDistanceModal,
    moveCopyDistanceMode,
    showSpecifyRotationModal,
    setShowSpecifyRotationModal,
    showSpecifyScaleModal,
    setShowSpecifyScaleModal,
    specifyScaleModalAxis,
    showFontListModal,
    setShowFontListModal,
    fontList,
    setFontList,
    autoSaveEnabled,
    setAutoSaveEnabled,
    reverseZoomDirection,
    setReverseZoomDirection,
    reverseGridScrollDirection,
    setReverseGridScrollDirection,
    incrementalSelection,
    setIncrementalSelection,
    mentoriWithoutCtrl,
    setMentoriWithoutCtrl,
    pinSideBar,
    setPinSideBar,
    continuousDistanceMarking,
    setContinuousDistanceMarking,
    reduceOneBlade,
    setReduceOneBlade,
    highlightActiveLayer,
    setHighlightActiveLayer,
    notchAngleDeg,
    setNotchAngleDeg,
    notchDepthMm,
    setNotchDepthMm,
    relativeAngleStepDeg,
    setRelativeAngleStepDeg,
    arcDrawMode,
    setArcDrawMode,
    arcRadiusMm,
    setArcRadiusMm,
    arcHalfMoonRatio,
    setArcHalfMoonRatio,
    tangentCircleMode,
    setTangentCircleMode,
    tangentCircleDispStep,
    setTangentCircleDispStep,
    dimensionLineTypeId,
    setDimensionLineTypeId,
    fillOnChange,
    setFillOnChange,
    drawEdges,
    setDrawEdges,
    drawFirstPos,
    setDrawFirstPos,
    centerLineDivisions,
    setCenterLineDivisions,
    markingDistanceMm,
    setMarkingDistanceMm,
    mandalaCircleTemplateName,
    setMandalaCircleTemplateName,
    translationMap,
    setTranslationMap,
    gridBackgroundMode,
    setGridBackgroundMode,
    showLengthAdjustModal,
    setShowLengthAdjustModal,
    showDimensionInspectorModal,
    setShowDimensionInspectorModal,
    showOptionsModal,
    setShowOptionsModal,
    leatherSimTextureRotationDeg,
    exportIncludeText,
    setExportIncludeText,
    exportIncludeTemplateMetadata,
    setExportIncludeTemplateMetadata,
    lineToolConstraint,
    setLineToolConstraint,
  } = uiState
  const {
    dimensionDefaults,
    setDimensionDefaults,
    forceFitLastPrick,
    setForceFitLastPrick,
    printCalibrationXPercent,
    setPrintCalibrationXPercent,
    printCalibrationYPercent,
    setPrintCalibrationYPercent,
    autoHideSidebar,
    setAutoHideSidebar,
    loadDemoOnStartup,
    setLoadDemoOnStartup,
    setShowHelpModal,
  } = panelState
  const setForceFitLastPrickAndSync = (value: boolean) => {
    setForceFitLastPrick(value)
    toolState.setStitchAutoPitchSettings((previous) => ({
      ...previous,
      forceFitLastHole: value,
    }))
  }
  const {
    selectedTemplateEntryId,
    templateRepositoryFolders,
    selectedTemplateFolderId,
    selectedCatalogShopId,
    setSelectedTemplateEntryId,
    setSelectedTemplateFolderId,
    setSelectedCatalogShopId,
  } = repositoryState
  const { activeLayerId } = layerState
  const { setTextFontFamily } = toolState
  const {
    fileInputRef,
    svgInputRef,
    tracingInputRef,
    patternPdfInputRef,
    backdropInputRef,
    templateImportInputRef,
    catalogImportInputRef,
    translationInputRef,
    fontInputRef,
  } = screenRefs
  const {
    activeLayer,
    activeLineType,
    shapeCountsByLineType,
    selectedShapeCount,
    selectedShapeIdSet,
    selectedStitchHole,
    selectedTemplateEntry,
    selectedHardwareMarker,
    activeExportRoleCount,
    layerColorsById,
  } = derivedState
  const { selectionBounds } = patternPieceSelection
  const { printOutputPlan, handleOpenPrintTiles } = printPreviewState
  const { handleFitView } = canvasController
  const { patternPieceChains } = derivedState
  const {
    documentCommands,
    exportActions,
    fileActions,
    selectionActions,
    transformActions,
    lineTypeActions,
    layerColorActions,
    constraintActions,
    sketchGroupActions,
    hardwareMarkerActions,
    geometryActions,
    creationController,
  } = actions
  const {
    handleUpdateSelectedShapePoint,
    handleResetExportOptions,
  } = documentCommands
  const { handleExportSvg, handleExportPdf, handleExportDxf, handleExportLaserSvg } = exportActions
  const {
    handleSaveJson,
    handleSaveLocalProject,
    handleLoadLocalProject,
    handleDeleteLocalProject,
    handleSaveLcc,
    handleExportGarmentJson,
    handleLoadJson,
    handleImportSvg,
    handleImportPatternPdf,
    handleLoadPreset,
    svgImportOptionsModalProps,
  } = fileActions
  const {
    handleSpecifyRotation,
    handleSpecifyScale,
    handleMirrorSelectionAcrossAxis,
  } = transformActions
  const {
    handleMoveSelectionByDistance,
    handleCopySelectionByDistance,
  } = selectionActions
  const {
    handleShowAllLineTypes,
    handleIsolateActiveLineType,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    handleUpdateActiveLineTypeColor,
    handleUpdateActiveLineTypeStrokeWidthMm,
    handleUpdateActiveLineTypeIgnoreInPrint,
    handleSelectShapesByActiveLineType,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleLinePaletteSelectAll,
    handleLinePaletteUnselectLineType,
    handleLinePaletteUnselectOthers,
  } = lineTypeActions
  const {
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  } = layerColorActions
  const {
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleClearAllSeamAllowances,
    handleToggleConstraintEnabled,
    handleDeleteConstraint,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleCreateOffsetGeometryFromSelection,
  } = constraintActions
  const {
    handleCreateSketchGroupFromSelection,
    handleCreateLinkedSketchGroup,
    handleRenameActiveSketchGroup,
    handleToggleActiveSketchGroupVisibility,
    handleToggleActiveSketchGroupLock,
    handleSetActiveSketchLink,
    handleClearActiveSketchLink,
    handleClearActiveSketchGroup,
    handleDeleteActiveSketchGroup,
    handleDuplicateActiveSketchGroup,
    handleSetActiveLayerAnnotation,
    handleSetActiveSketchAnnotation,
  } = sketchGroupActions
  const { handleDeleteSelectedHardwareMarker, handleUpdateSelectedHardwareMarker } = hardwareMarkerActions
  const {
    handleResizeShapes,
  } = geometryActions
  const {
    stitchSimulatorResult,
    handleApplyTextDefaultsToSelection,
    handleGenerateBoxStitch,
    handleApplyBoxStitchHelper,
    handleGenerateMandalaRadial,
    handleGenerateSpiral,
    handleGenerateGoldenGuides,
    handleGenerateWhiteSilverGuides,
    handleUseSelectionAsMandalaCenter,
    handleGenerateMandalaIntersections,
    handleClearMandalaIntersections,
    handleGenerateWizardPattern,
    handleGenerateLetterStamp,
  } = creationController
  const {
    handleSaveTemplateToRepository,
    handleDeleteTemplateFromRepository,
    handleLoadTemplateAsDocument,
    handleInsertTemplateIntoDocument,
    handleSeparateTemplateIntoShapes,
    handleStampTemplateAlongSelectedShape,
    handleExportTemplateRepository,
    handleImportTemplateRepositoryFile,
    handleImportCatalogFile,
    handleCreateCatalogShop,
    handleDeleteCatalogShop,
    handleExportCatalogShop,
    handleMoveTemplateEntry,
    handleSortTemplates,
    handleCreateTemplateFolder,
    handleRenameTemplateFolder,
    handleDeleteTemplateFolder,
    handleMoveTemplateToFolder,
    handleMoveTemplateFolderToFolder,
    handleFlipTemplate,
    handleMoveCatalogShop,
    handleSortCatalogShops,
    handleUpdateCatalogShop,
    handleUpdateCatalogGroup,
    handleUpdateCatalogItem,
    handleCreateCatalogGroup,
    handleDeleteCatalogGroup,
    handleDuplicateCatalogGroup,
    handleMoveCatalogGroup,
    handleCreateCatalogItem,
    handleDuplicateCatalogItem,
    handleDeleteCatalogItem,
    handleMoveCatalogItemToGroup,
  } = templateActions
  const {
    handleLoadAiBuilderDocument,
    handleInsertAiBuilderDocument,
  } = aiBuilderActions
  const {
    handleUpdateTracingOverlay,
    handleDeleteTracingOverlay,
    handleSetPdfTracingPage,
    handleImportTracing,
  } = tracingActions
  const {
    handleImportBackdrop,
    handleDeleteActiveBackdrop,
    handleUpdateBackdrop,
    handleBackdropUndo,
    handleBackdropRedo,
    activeBackdrop,
  } = backdropActions
  const {
    handleBooleanOp,
    handleClipperOffset,
    handleTextToPath,
    handleFontInputChange,
  } = assetCommands

  return useEditorOverlayViewModel({
    modalStack: {
      shapeCountsByLineType,
      selectedShapeCount,
      handleShowAllLineTypes,
      handleIsolateActiveLineType,
      handleUpdateActiveLineTypeRole,
      handleUpdateActiveLineTypeStyle,
      handleUpdateActiveLineTypeColor,
      handleUpdateActiveLineTypeStrokeWidthMm,
      handleUpdateActiveLineTypeIgnoreInPrint,
      handleSelectShapesByActiveLineType,
      handleAssignSelectedToActiveLineType,
      handleClearShapeSelection,
      handleLinePaletteSelectAllVisible: () => handleLinePaletteSelectAll(lineTypes),
      handleLinePaletteUnselectActive: () => {
        if (activeLineType) handleLinePaletteUnselectLineType(activeLineType.id)
      },
      handleLinePaletteUnselectOtherThanActive: () => {
        if (activeLineType) handleLinePaletteUnselectOthers(activeLineType.id)
      },
      layerColorsById,
      handleSetLayerColorOverride,
      handleClearLayerColorOverride,
      handleResetLayerColors,
      handleSaveJson,
      activeLocalDocumentId: documentState.activeLocalDocumentId,
      handleSaveLocalProject,
      handleLoadLocalProject,
      handleDeleteLocalProject,
      handleExportGarmentJson,
      handleSaveLcc,
      handleExportSvg,
      handleExportPdf,
      handleExportDxf,
      handleExportLaserSvg,
      activeExportRoleCount,
      handleResetExportOptions,
      templateRepository: repositoryState.templateRepository,
      templateRepositoryFolders,
      catalogRepository: mergedCatalogRepository,
      selectedTemplateEntryId,
      selectedTemplateEntry,
      selectedTemplateFolderId,
      selectedCatalogShopId,
      setSelectedTemplateEntryId,
      setSelectedTemplateFolderId,
      setSelectedCatalogShopId,
      handleSaveTemplateToRepository,
      handleExportTemplateRepository,
      templateImportInputRef,
      catalogImportInputRef,
      handleLoadPreset,
      handleLoadTemplateAsDocument,
      handleInsertTemplateIntoDocument,
      handleSeparateTemplateIntoShapes,
      handleStampTemplateAlongSelectedShape,
      handleDeleteTemplateFromRepository,
      handleMoveTemplateEntry,
      handleSortTemplates,
      handleCreateTemplateFolder,
      handleRenameTemplateFolder,
      handleDeleteTemplateFolder,
      handleMoveTemplateToFolder,
      handleMoveTemplateFolderToFolder,
      handleFlipTemplate,
      handleCreateCatalogShop,
      handleDeleteCatalogShop,
      handleExportCatalogShop,
      handleMoveCatalogShop,
      handleSortCatalogShops,
      handleUpdateCatalogShop,
      handleUpdateCatalogGroup,
      handleUpdateCatalogItem,
      handleCreateCatalogGroup,
      handleDeleteCatalogGroup,
      handleDuplicateCatalogGroup,
      handleMoveCatalogGroup,
      handleCreateCatalogItem,
      handleDuplicateCatalogItem,
      handleDeleteCatalogItem,
      handleMoveCatalogItemToGroup,
      handleAlignSelection,
      handleAlignSelectionToGrid,
      activeLayer,
      handleCreateSketchGroupFromSelection,
      handleCreateLinkedSketchGroup,
      handleDuplicateActiveSketchGroup,
      handleRenameActiveSketchGroup,
      handleToggleActiveSketchGroupVisibility,
      handleToggleActiveSketchGroupLock,
      handleSetActiveSketchLink,
      handleClearActiveSketchLink,
      handleClearActiveSketchGroup,
      handleDeleteActiveSketchGroup,
      handleSetActiveLayerAnnotation,
      handleSetActiveSketchAnnotation,
      handleAddEdgeConstraintFromSelection,
      handleAddAlignConstraintsFromSelection,
      handleApplyConstraints,
      handleToggleConstraintEnabled,
      handleDeleteConstraint,
      handleApplySeamAllowanceToSelection,
      handleClearSeamAllowanceOnSelection,
      handleClearAllSeamAllowances,
      handleBevelSelectedCorner,
      handleRoundSelectedCorner,
      handleCreateOffsetGeometryFromSelection,
      handleCreateBoxStitchFromSelection: creationController.handleOpenBoxStitchHelperModal,
      selectedEditableShape,
      handleUpdateSelectedShapePoint,
      handleApplyTextDefaultsToSelection,
      selectedHardwareMarker,
      handleUpdateSelectedHardwareMarker,
      handleDeleteSelectedHardwareMarker,
      handleBooleanOp,
      handleClipperOffset,
      handleTextToPath,
      handleOpenNesting: () => setShowNestingModal(true),
      tracingInputRef,
      handleDeleteTracingOverlay,
      handleUpdateTracingOverlay,
      handleSetPdfTracingPage,
      printPlan: printOutputPlan,
      handleFitView,
      handleOpenPrintTiles,
      handleLoadAiBuilderDocument,
      handleInsertAiBuilderDocument,
    },
    overlay: {
      showStitchSimulatorModal,
      setShowStitchSimulatorModal,
      stitchSimulatorSettings,
      setStitchSimulatorSettings,
      stitchSimulatorResult,
      stitchHoles,
      selectedStitchHole,
      showBoxStitchHelperModal,
      setShowBoxStitchHelperModal,
      boxStitchHelperSettings,
      handleApplyBoxStitchHelper,
      selectedShapeCount,
      showBoxStitchModal,
      setShowBoxStitchModal,
      handleGenerateBoxStitch,
      activeLayerId,
      activeLineTypeId,
      showMandalaModal,
      setShowMandalaModal,
      handleGenerateMandalaRadial,
      handleGenerateSpiral,
      handleGenerateGoldenGuides,
      handleGenerateWhiteSilverGuides,
      handleMirrorSelectionAcrossAxis,
      handleUseSelectionAsMandalaCenter,
      handleGenerateMandalaIntersections,
      handleClearMandalaIntersections,
      setShowHelpModal,
      showWizardModal,
      setShowWizardModal,
      handleGenerateWizardPattern,
      showBackdropModal,
      setShowBackdropModal,
      backdrops,
      activeBackdrop,
      onSelectBackdrop: setActiveBackdropId,
      onImportBackdrop: () => backdropInputRef.current?.click(),
      onDeleteActiveBackdrop: handleDeleteActiveBackdrop,
      onUpdateBackdrop: handleUpdateBackdrop,
      onBackdropUndo: handleBackdropUndo,
      onBackdropRedo: handleBackdropRedo,
      backdropFileInputRef: backdropInputRef,
      onBackdropFileChange: handleImportBackdrop,
      showLetterStampModal,
      setShowLetterStampModal,
      handleGenerateLetterStamp,
      showChangeShapeSizeModal,
      setShowChangeShapeSizeModal,
      handleResizeShapes,
      selectionBounds,
      showMoveCopyDistanceModal,
      setShowMoveCopyDistanceModal,
      moveCopyDistanceMode,
      handleMoveSelectionByDistance,
      handleCopySelectionByDistance,
      showSpecifyRotationModal,
      setShowSpecifyRotationModal,
      handleSpecifyRotation,
      showSpecifyScaleModal,
      setShowSpecifyScaleModal,
      specifyScaleModalAxis,
      handleSpecifyScale,
      showFontListModal,
      setShowFontListModal,
      fontList,
      setFontList,
      setTextFontFamily,
      showOptionsModal,
      setShowOptionsModal,
      autoSaveEnabled,
      reverseZoomDirection,
      reverseGridScrollDirection,
      incrementalSelection,
      mentoriWithoutCtrl,
      exportIncludeText,
      exportIncludeTemplateMetadata,
      setAutoSaveEnabled,
      setReverseZoomDirection,
      setReverseGridScrollDirection,
      setIncrementalSelection,
      setMentoriWithoutCtrl,
      pinSideBar,
      setPinSideBar,
      continuousDistanceMarking,
      setContinuousDistanceMarking,
      reduceOneBlade,
      setReduceOneBlade,
      highlightActiveLayer,
      setHighlightActiveLayer,
      notchAngleDeg,
      setNotchAngleDeg,
      notchDepthMm,
      setNotchDepthMm,
      relativeAngleStepDeg,
      setRelativeAngleStepDeg,
      arcDrawMode,
      setArcDrawMode,
      arcRadiusMm,
      setArcRadiusMm,
      arcHalfMoonRatio,
      setArcHalfMoonRatio,
      tangentCircleMode,
      setTangentCircleMode,
      tangentCircleDispStep,
      setTangentCircleDispStep,
      dimensionLineTypeId,
      setDimensionLineTypeId,
      optionsLineTypes: lineTypes,
      fillOnChange,
      setFillOnChange,
      drawEdges,
      setDrawEdges,
      drawFirstPos,
      setDrawFirstPos,
      centerLineDivisions,
      setCenterLineDivisions,
      markingDistanceMm,
      setMarkingDistanceMm,
      mandalaCircleTemplateName,
      setMandalaCircleTemplateName,
      setExportIncludeText,
      setExportIncludeTemplateMetadata,
      leatherSimTextureRotationDeg,
      lineToolConstraint,
      setLineToolConstraint,
      gridBackgroundMode,
      setGridBackgroundMode,
      dimensionDefaults,
      setDimensionDefaults,
      forceFitLastPrick,
      setForceFitLastPrick: setForceFitLastPrickAndSync,
      autoPitchSettings: toolState.stitchAutoPitchSettings,
      setAutoPitchSettings: (next: import('../../editor-types').StitchAutoPitchSettings) => {
        toolState.setStitchAutoPitchSettings(next)
        setForceFitLastPrick(next.forceFitLastHole)
      },
      setBoxStitchHelperSettings,
      printCalibrationXPercent,
      setPrintCalibrationXPercent,
      printCalibrationYPercent,
      setPrintCalibrationYPercent,
      autoHideSidebar,
      setAutoHideSidebar,
      loadDemoOnStartup,
      setLoadDemoOnStartup,
      showLengthAdjustModal,
      setShowLengthAdjustModal,
      showDimensionInspectorModal,
      setShowDimensionInspectorModal,
      dimensionLines,
      setDimensionLines,
      shapes,
      selectedShapeIdSet,
      setShapes,
      showProjectMemoModal,
      setShowProjectMemoModal,
      projectMemo,
      setProjectMemo,
      isMobileLayout,
      showPieceInspectorModal,
      setShowPieceInspectorModal,
      pieceInspectorContentProps,
      showNestingModal,
      setShowNestingModal,
      patternPieces,
      pieceGrainlines,
      patternPieceChainsByShapeId: patternPieceChains.byShapeId,
      fileInputRef,
      svgInputRef,
      tracingInputRef,
      patternPdfInputRef,
      svgImportOptionsModalProps,
      templateImportInputRef,
      catalogImportInputRef,
      translationInputRef,
      handleLoadJson,
      handleImportSvg,
      handleImportPatternPdf,
      handleImportTracing,
      handleImportTemplateRepositoryFile,
      handleImportCatalogFile,
      setTranslationMap,
      translationMap,
      fontInputRef,
      onFontInputChange: handleFontInputChange,
      setStatus,
    },
  })
}
