import type { Dispatch, SetStateAction } from 'react'
import type { UseEditorScreenShellsParams } from '../../editorScreenShellTypes'
import type { BoxStitchHelperSettings } from '../../ops/box-stitch-settings'
import type { StitchSimulatorSettings } from '../../ops/stitch-simulator-ops'
import type { useAiBuilderActions } from '../../hooks/useAiBuilderActions'
import type { useBackdropActions } from '../../hooks/useBackdropActions'
import type { useEditorAssetCommands } from '../../useEditorAssetCommands'
import type { useTemplateActions } from '../../hooks/useTemplateActions'
import type { useTracingActions } from '../../hooks/useTracingActions'
import {
  useEditorOverlayViewModel,
  type UseEditorOverlayViewModelParams,
} from './useEditorOverlayViewModel'

type OverlayPropsParams = UseEditorOverlayViewModelParams['overlay']

type UseEditorScreenOverlayParams = UseEditorScreenShellsParams & {
  mergedCatalogRepository: UseEditorScreenShellsParams['repositoryState']['catalogRepository']
  stitchSimulatorSettings: StitchSimulatorSettings
  setStitchSimulatorSettings: Dispatch<SetStateAction<StitchSimulatorSettings>>
  boxStitchHelperSettings: BoxStitchHelperSettings
  showPieceInspectorModal: boolean
  setShowPieceInspectorModal: Dispatch<SetStateAction<boolean>>
  pieceInspectorContentProps: OverlayPropsParams['pieceInspectorContentProps']
  templateActions: ReturnType<typeof useTemplateActions>
  aiBuilderActions: ReturnType<typeof useAiBuilderActions>
  tracingActions: ReturnType<typeof useTracingActions>
  backdropActions: ReturnType<typeof useBackdropActions>
  assetCommands: ReturnType<typeof useEditorAssetCommands>
}

export function useEditorScreenOverlay({
  documentState,
  uiState,
  repositoryState,
  layerState,
  toolState,
  screenRefs,
  derivedState,
  canvasController,
  patternPieceSelection,
  printPreviewState,
  selectedEditableShape,
  actions,
  mergedCatalogRepository,
  stitchSimulatorSettings,
  setStitchSimulatorSettings,
  boxStitchHelperSettings,
  showPieceInspectorModal,
  setShowPieceInspectorModal,
  pieceInspectorContentProps,
  templateActions,
  aiBuilderActions,
  tracingActions,
  backdropActions,
  assetCommands,
}: UseEditorScreenOverlayParams) {
  const {
    lineTypes,
    activeLineTypeId,
    shapes,
    setShapes,
    stitchHoles,
    backdrops,
    setActiveBackdropId,
    projectMemo,
    setProjectMemo,
    patternPieces,
    pieceGrainlines,
  } = documentState
  const {
    setStatus,
    isMobileLayout,
    showProjectMemoModal,
    setShowProjectMemoModal,
    showNestingModal,
    setShowNestingModal,
    showStitchSimulatorModal,
    setShowStitchSimulatorModal,
    showBoxStitchHelperModal,
    setShowBoxStitchHelperModal,
    showBoxStitchModal,
    setShowBoxStitchModal,
    showMandalaModal,
    setShowMandalaModal,
    showWizardModal,
    setShowWizardModal,
    showBackdropModal,
    setShowBackdropModal,
    showLetterStampModal,
    setShowLetterStampModal,
    showChangeShapeSizeModal,
    setShowChangeShapeSizeModal,
    showMoveCopyDistanceModal,
    setShowMoveCopyDistanceModal,
    moveCopyDistanceMode,
    showSpecifyRotationModal,
    setShowSpecifyRotationModal,
    showSpecifyScaleModal,
    setShowSpecifyScaleModal,
    specifyScaleModalAxis,
    showFontListModal,
    setShowFontListModal,
    fontList,
    setFontList,
    autoSaveEnabled,
    setAutoSaveEnabled,
    reverseZoomDirection,
    setReverseZoomDirection,
    incrementalSelection,
    setIncrementalSelection,
    mentoriWithoutCtrl,
    setMentoriWithoutCtrl,
    setTranslationMap,
    gridBackgroundMode,
    setGridBackgroundMode,
    showLengthAdjustModal,
    setShowLengthAdjustModal,
    showOptionsModal,
    setShowOptionsModal,
    leatherSimTextureRotationDeg,
    exportIncludeText,
    setExportIncludeText,
    exportIncludeTemplateMetadata,
    setExportIncludeTemplateMetadata,
    lineToolConstraint,
    setLineToolConstraint,
  } = uiState
  const {
    selectedTemplateEntryId,
    selectedCatalogShopId,
    setSelectedTemplateEntryId,
    setSelectedCatalogShopId,
  } = repositoryState
  const { activeLayerId } = layerState
  const { setTextFontFamily } = toolState
  const {
    fileInputRef,
    svgInputRef,
    tracingInputRef,
    backdropInputRef,
    templateImportInputRef,
    catalogImportInputRef,
    translationInputRef,
    fontInputRef,
  } = screenRefs
  const {
    activeLayer,
    activeLineType,
    shapeCountsByLineType,
    selectedShapeCount,
    selectedShapeIdSet,
    selectedStitchHole,
    selectedTemplateEntry,
    selectedHardwareMarker,
    activeExportRoleCount,
    layerColorsById,
  } = derivedState
  const { selectionBounds } = patternPieceSelection
  const { printOutputPlan, handleOpenPrintTiles } = printPreviewState
  const { handleFitView } = canvasController
  const { patternPieceChains } = derivedState
  const {
    documentCommands,
    exportActions,
    fileActions,
    selectionActions,
    transformActions,
    lineTypeActions,
    layerColorActions,
    constraintActions,
    sketchGroupActions,
    hardwareMarkerActions,
    geometryActions,
    creationController,
  } = actions
  const {
    handleUpdateSelectedShapePoint,
    handleResetExportOptions,
  } = documentCommands
  const { handleExportSvg, handleExportPdf, handleExportDxf, handleExportLaserSvg } = exportActions
  const {
    handleSaveJson,
    handleSaveLocalProject,
    handleLoadLocalProject,
    handleDeleteLocalProject,
    handleSaveLcc,
    handleExportGarmentJson,
    handleLoadJson,
    handleImportSvg,
    handleLoadPreset,
    svgImportOptionsModalProps,
  } = fileActions
  const {
    handleSpecifyRotation,
    handleSpecifyScale,
  } = transformActions
  const {
    handleMoveSelectionByDistance,
    handleCopySelectionByDistance,
  } = selectionActions
  const {
    handleShowAllLineTypes,
    handleIsolateActiveLineType,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    handleUpdateActiveLineTypeColor,
    handleUpdateActiveLineTypeStrokeWidthMm,
    handleUpdateActiveLineTypeIgnoreInPrint,
    handleSelectShapesByActiveLineType,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleLinePaletteSelectAll,
    handleLinePaletteUnselectLineType,
    handleLinePaletteUnselectOthers,
  } = lineTypeActions
  const {
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  } = layerColorActions
  const {
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleClearAllSeamAllowances,
    handleToggleConstraintEnabled,
    handleDeleteConstraint,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleCreateOffsetGeometryFromSelection,
  } = constraintActions
  const {
    handleCreateSketchGroupFromSelection,
    handleCreateLinkedSketchGroup,
    handleRenameActiveSketchGroup,
    handleToggleActiveSketchGroupVisibility,
    handleToggleActiveSketchGroupLock,
    handleSetActiveSketchLink,
    handleClearActiveSketchLink,
    handleClearActiveSketchGroup,
    handleDeleteActiveSketchGroup,
    handleDuplicateActiveSketchGroup,
    handleSetActiveLayerAnnotation,
    handleSetActiveSketchAnnotation,
  } = sketchGroupActions
  const { handleDeleteSelectedHardwareMarker, handleUpdateSelectedHardwareMarker } = hardwareMarkerActions
  const {
    handleResizeShapes,
  } = geometryActions
  const {
    stitchSimulatorResult,
    handleApplyTextDefaultsToSelection,
    handleGenerateBoxStitch,
    handleApplyBoxStitchHelper,
    handleGenerateMandalaRadial,
    handleGenerateSpiral,
    handleGenerateGoldenGuides,
    handleGenerateWhiteSilverGuides,
    handleGenerateWizardPattern,
    handleGenerateLetterStamp,
  } = creationController
  const {
    handleSaveTemplateToRepository,
    handleDeleteTemplateFromRepository,
    handleLoadTemplateAsDocument,
    handleInsertTemplateIntoDocument,
    handleExportTemplateRepository,
    handleImportTemplateRepositoryFile,
    handleImportCatalogFile,
    handleDeleteCatalogShop,
    handleExportCatalogShop,
    handleMoveTemplateEntry,
    handleSortTemplates,
    handleMoveCatalogShop,
    handleSortCatalogShops,
    handleUpdateCatalogShop,
    handleUpdateCatalogGroup,
    handleUpdateCatalogItem,
  } = templateActions
  const {
    handleLoadAiBuilderDocument,
    handleInsertAiBuilderDocument,
  } = aiBuilderActions
  const {
    handleUpdateTracingOverlay,
    handleDeleteTracingOverlay,
    handleSetPdfTracingPage,
    handleImportTracing,
  } = tracingActions
  const {
    handleImportBackdrop,
    handleDeleteActiveBackdrop,
    handleUpdateBackdrop,
    handleBackdropUndo,
    handleBackdropRedo,
    activeBackdrop,
  } = backdropActions
  const {
    handleBooleanOp,
    handleClipperOffset,
    handleTextToPath,
    handleFontInputChange,
  } = assetCommands

  return useEditorOverlayViewModel({
    modalStack: {
      shapeCountsByLineType,
      selectedShapeCount,
      handleShowAllLineTypes,
      handleIsolateActiveLineType,
      handleUpdateActiveLineTypeRole,
      handleUpdateActiveLineTypeStyle,
      handleUpdateActiveLineTypeColor,
      handleUpdateActiveLineTypeStrokeWidthMm,
      handleUpdateActiveLineTypeIgnoreInPrint,
      handleSelectShapesByActiveLineType,
      handleAssignSelectedToActiveLineType,
      handleClearShapeSelection,
      handleLinePaletteSelectAllVisible: () => handleLinePaletteSelectAll(lineTypes),
      handleLinePaletteUnselectActive: () => {
        if (activeLineType) handleLinePaletteUnselectLineType(activeLineType.id)
      },
      handleLinePaletteUnselectOtherThanActive: () => {
        if (activeLineType) handleLinePaletteUnselectOthers(activeLineType.id)
      },
      layerColorsById,
      handleSetLayerColorOverride,
      handleClearLayerColorOverride,
      handleResetLayerColors,
      handleSaveJson,
      activeLocalDocumentId: documentState.activeLocalDocumentId,
      handleSaveLocalProject,
      handleLoadLocalProject,
      handleDeleteLocalProject,
      handleExportGarmentJson,
      handleSaveLcc,
      handleExportSvg,
      handleExportPdf,
      handleExportDxf,
      handleExportLaserSvg,
      activeExportRoleCount,
      handleResetExportOptions,
      templateRepository: repositoryState.templateRepository,
      catalogRepository: mergedCatalogRepository,
      selectedTemplateEntryId,
      selectedTemplateEntry,
      selectedCatalogShopId,
      setSelectedTemplateEntryId,
      setSelectedCatalogShopId,
      handleSaveTemplateToRepository,
      handleExportTemplateRepository,
      templateImportInputRef,
      catalogImportInputRef,
      handleLoadPreset,
      handleLoadTemplateAsDocument,
      handleInsertTemplateIntoDocument,
      handleDeleteTemplateFromRepository,
      handleMoveTemplateEntry,
      handleSortTemplates,
      handleDeleteCatalogShop,
      handleExportCatalogShop,
      handleMoveCatalogShop,
      handleSortCatalogShops,
      handleUpdateCatalogShop,
      handleUpdateCatalogGroup,
      handleUpdateCatalogItem,
      handleAlignSelection,
      handleAlignSelectionToGrid,
      activeLayer,
      handleCreateSketchGroupFromSelection,
      handleCreateLinkedSketchGroup,
      handleDuplicateActiveSketchGroup,
      handleRenameActiveSketchGroup,
      handleToggleActiveSketchGroupVisibility,
      handleToggleActiveSketchGroupLock,
      handleSetActiveSketchLink,
      handleClearActiveSketchLink,
      handleClearActiveSketchGroup,
      handleDeleteActiveSketchGroup,
      handleSetActiveLayerAnnotation,
      handleSetActiveSketchAnnotation,
      handleAddEdgeConstraintFromSelection,
      handleAddAlignConstraintsFromSelection,
      handleApplyConstraints,
      handleToggleConstraintEnabled,
      handleDeleteConstraint,
      handleApplySeamAllowanceToSelection,
      handleClearSeamAllowanceOnSelection,
      handleClearAllSeamAllowances,
      handleBevelSelectedCorner,
      handleRoundSelectedCorner,
      handleCreateOffsetGeometryFromSelection,
      handleCreateBoxStitchFromSelection: creationController.handleOpenBoxStitchHelperModal,
      selectedEditableShape,
      handleUpdateSelectedShapePoint,
      handleApplyTextDefaultsToSelection,
      selectedHardwareMarker,
      handleUpdateSelectedHardwareMarker,
      handleDeleteSelectedHardwareMarker,
      handleBooleanOp,
      handleClipperOffset,
      handleTextToPath,
      handleOpenNesting: () => setShowNestingModal(true),
      tracingInputRef,
      handleDeleteTracingOverlay,
      handleUpdateTracingOverlay,
      handleSetPdfTracingPage,
      printPlan: printOutputPlan,
      handleFitView,
      handleOpenPrintTiles,
      handleLoadAiBuilderDocument,
      handleInsertAiBuilderDocument,
    },
    overlay: {
      showStitchSimulatorModal,
      setShowStitchSimulatorModal,
      stitchSimulatorSettings,
      setStitchSimulatorSettings,
      stitchSimulatorResult,
      stitchHoles,
      selectedStitchHole,
      showBoxStitchHelperModal,
      setShowBoxStitchHelperModal,
      boxStitchHelperSettings,
      handleApplyBoxStitchHelper,
      selectedShapeCount,
      showBoxStitchModal,
      setShowBoxStitchModal,
      handleGenerateBoxStitch,
      activeLayerId,
      activeLineTypeId,
      showMandalaModal,
      setShowMandalaModal,
      handleGenerateMandalaRadial,
      handleGenerateSpiral,
      handleGenerateGoldenGuides,
      handleGenerateWhiteSilverGuides,
      showWizardModal,
      setShowWizardModal,
      handleGenerateWizardPattern,
      showBackdropModal,
      setShowBackdropModal,
      backdrops,
      activeBackdrop,
      onSelectBackdrop: setActiveBackdropId,
      onImportBackdrop: () => backdropInputRef.current?.click(),
      onDeleteActiveBackdrop: handleDeleteActiveBackdrop,
      onUpdateBackdrop: handleUpdateBackdrop,
      onBackdropUndo: handleBackdropUndo,
      onBackdropRedo: handleBackdropRedo,
      backdropFileInputRef: backdropInputRef,
      onBackdropFileChange: handleImportBackdrop,
      showLetterStampModal,
      setShowLetterStampModal,
      handleGenerateLetterStamp,
      showChangeShapeSizeModal,
      setShowChangeShapeSizeModal,
      handleResizeShapes,
      selectionBounds,
      showMoveCopyDistanceModal,
      setShowMoveCopyDistanceModal,
      moveCopyDistanceMode,
      handleMoveSelectionByDistance,
      handleCopySelectionByDistance,
      showSpecifyRotationModal,
      setShowSpecifyRotationModal,
      handleSpecifyRotation,
      showSpecifyScaleModal,
      setShowSpecifyScaleModal,
      specifyScaleModalAxis,
      handleSpecifyScale,
      showFontListModal,
      setShowFontListModal,
      fontList,
      setFontList,
      setTextFontFamily,
      showOptionsModal,
      setShowOptionsModal,
      autoSaveEnabled,
      reverseZoomDirection,
      incrementalSelection,
      mentoriWithoutCtrl,
      exportIncludeText,
      exportIncludeTemplateMetadata,
      setAutoSaveEnabled,
      setReverseZoomDirection,
      setIncrementalSelection,
      setMentoriWithoutCtrl,
      setExportIncludeText,
      setExportIncludeTemplateMetadata,
      leatherSimTextureRotationDeg,
      lineToolConstraint,
      setLineToolConstraint,
      gridBackgroundMode,
      setGridBackgroundMode,
      showLengthAdjustModal,
      setShowLengthAdjustModal,
      shapes,
      selectedShapeIdSet,
      setShapes,
      showProjectMemoModal,
      setShowProjectMemoModal,
      projectMemo,
      setProjectMemo,
      isMobileLayout,
      showPieceInspectorModal,
      setShowPieceInspectorModal,
      pieceInspectorContentProps,
      showNestingModal,
      setShowNestingModal,
      patternPieces,
      pieceGrainlines,
      patternPieceChainsByShapeId: patternPieceChains.byShapeId,
      fileInputRef,
      svgInputRef,
      tracingInputRef,
      svgImportOptionsModalProps,
      templateImportInputRef,
      catalogImportInputRef,
      translationInputRef,
      handleLoadJson,
      handleImportSvg,
      handleImportTracing,
      handleImportTemplateRepositoryFile,
      handleImportCatalogFile,
      setTranslationMap,
      fontInputRef,
      onFontInputChange: handleFontInputChange,
      setStatus,
    },
  })
}
