import type { AiBuilderDocumentV1 } from './ai-builder-types'

export const AI_BUILDER_EXAMPLES: readonly AiBuilderDocumentV1[] = [
  {
    schema_version: 1,
    document_name: 'card_sleeve_front',
    units: 'mm',
    layers: [
      { id: 'body', name: 'Body' },
      { id: 'markings', name: 'Markings' },
    ],
    entities: [
      {
        id: 'sleeve_outline',
        type: 'rectangle',
        layer_id: 'body',
        x: -164,
        y: -102,
        width: 328,
        height: 204,
        line_role: 'cut',
      },
      {
        id: 'thumb_cutout',
        type: 'arc',
        layer_id: 'body',
        start: { x: -58, y: -84 },
        mid: { x: 0, y: -126 },
        end: { x: 58, y: -84 },
        line_role: 'cut',
      },
      {
        id: 'title_label',
        type: 'text',
        layer_id: 'markings',
        position: { x: -54, y: 136 },
        value: 'Card Sleeve',
        line_role: 'mark',
        font_size_mm: 10,
      },
    ],
  },
  {
    schema_version: 1,
    document_name: 'bifold_wallet_shell',
    units: 'mm',
    layers: [
      { id: 'shell', name: 'Outer Shell' },
      { id: 'guides', name: 'Guides' },
    ],
    entities: [
      {
        id: 'shell_outline',
        type: 'rectangle',
        layer_id: 'shell',
        x: -220,
        y: -140,
        width: 440,
        height: 280,
        line_role: 'cut',
      },
      {
        id: 'center_guide',
        type: 'line',
        layer_id: 'guides',
        start: { x: 0, y: -140 },
        end: { x: 0, y: 140 },
        line_role: 'guide',
      },
      {
        id: 'wallet_center_fold',
        type: 'fold',
        start: { x: 0, y: -140 },
        end: { x: 0, y: 140 },
        name: 'Wallet Center Fold',
        direction: 'mountain',
        angle_deg: 58,
        max_angle_deg: 180,
        radius_mm: 1.4,
        thickness_mm: 1.7,
        neutral_axis_ratio: 0.5,
        stiffness: 0.35,
        clearance_mm: 0.25,
      },
    ],
  },
  {
    schema_version: 1,
    document_name: 'curved_pocket_panel',
    units: 'mm',
    layers: [
      { id: 'panel', name: 'Pocket Panel' },
      { id: 'stitching', name: 'Stitching' },
    ],
    entities: [
      {
        id: 'slot_curve',
        type: 'bezier',
        layer_id: 'panel',
        start: { x: -188, y: -50 },
        control: { x: -106, y: -88 },
        end: { x: -24, y: -50 },
        line_role: 'cut',
      },
      {
        id: 'stitch_run',
        type: 'line',
        layer_id: 'stitching',
        start: { x: -194, y: 106 },
        end: { x: -20, y: 106 },
        line_role: 'stitch',
      },
      {
        id: 'brand_mark',
        type: 'text',
        layer_id: 'panel',
        position: { x: -74, y: 122 },
        value: 'Heritage',
        transform: 'arch',
        radius_mm: 52,
        sweep_deg: 110,
      },
    ],
  },
] as const
