import type { AiBuilderDocumentV1 } from './ai-builder-types'

export const AI_BUILDER_EXAMPLES: readonly AiBuilderDocumentV1[] = [
  {
    schema_version: 1,
    document_name: 'card_sleeve_front',
    units: 'mm',
    layers: [
      { id: 'body', name: 'Body' },
      { id: 'markings', name: 'Markings' },
    ],
    entities: [
      {
        id: 'sleeve_outline',
        type: 'rectangle',
        layer_id: 'body',
        x: -164,
        y: -102,
        width: 328,
        height: 204,
        line_role: 'cut',
      },
      {
        id: 'thumb_cutout',
        type: 'arc',
        layer_id: 'body',
        start: { x: -58, y: -84 },
        mid: { x: 0, y: -126 },
        end: { x: 58, y: -84 },
        line_role: 'cut',
      },
      {
        id: 'sleeve_bottom_stitching',
        type: 'stitch_path',
        layer_id: 'body',
        path_type: 'line',
        start: { x: -146, y: 82 },
        end: { x: 146, y: 82 },
        pitch_mm: 4,
        hole_type: 'slit',
        render_shape: 'diamond',
        width_mm: 1.2,
        height_mm: 0.55,
        tilt_deg: 35,
      },
      {
        id: 'sleeve_front_piece',
        type: 'pattern_piece',
        layer_id: 'body',
        boundary_entity_id: 'sleeve_outline',
        internal_entity_ids: ['sleeve_bottom_stitching', 'thumb_cutout'],
        name: 'Card Sleeve Front',
        quantity: 1,
        material_side: 'grain',
      },
      {
        id: 'sleeve_front_allowance',
        type: 'seam_allowance',
        piece_id: 'sleeve_front_piece',
        default_offset_mm: 3,
      },
      {
        id: 'title_label',
        type: 'text',
        layer_id: 'markings',
        position: { x: -54, y: 136 },
        value: 'Card Sleeve',
        line_role: 'mark',
        font_size_mm: 10,
      },
    ],
  },
  {
    schema_version: 1,
    document_name: 'bifold_wallet_shell',
    units: 'mm',
    layers: [
      { id: 'shell', name: 'Outer Shell' },
      { id: 'guides', name: 'Guides' },
    ],
    entities: [
      {
        id: 'shell_outline',
        type: 'rectangle',
        layer_id: 'shell',
        x: -220,
        y: -140,
        width: 440,
        height: 280,
        line_role: 'cut',
      },
      {
        id: 'center_guide',
        type: 'line',
        layer_id: 'guides',
        start: { x: 0, y: -140 },
        end: { x: 0, y: 140 },
        line_role: 'guide',
      },
      {
        id: 'wallet_center_fold',
        type: 'fold',
        start: { x: 0, y: -140 },
        end: { x: 0, y: 140 },
        name: 'Wallet Center Fold',
        direction: 'mountain',
        angle_deg: 58,
        max_angle_deg: 180,
        radius_mm: 1.4,
        thickness_mm: 1.7,
        neutral_axis_ratio: 0.5,
        stiffness: 0.35,
        clearance_mm: 0.25,
      },
    ],
  },
  {
    schema_version: 1,
    document_name: 'bifold_wallet_with_card_pockets',
    units: 'mm',
    layers: [
      { id: 'outer_shell', name: 'Outer Shell' },
      { id: 'bill_liner', name: 'Bill Pocket Liner' },
      { id: 'left_stack', name: 'Left Card Pocket Stack' },
      { id: 'right_stack', name: 'Right Card Pocket Stack' },
      { id: 'clearance_guides', name: 'Bill and Card Clearance Guides' },
      { id: 'wallet_markings', name: 'Markings' },
    ],
    entities: [
      {
        id: 'shell_outline',
        type: 'rectangle',
        layer_id: 'outer_shell',
        x: -116,
        y: -48,
        width: 232,
        height: 96,
        line_role: 'cut',
      },
      {
        id: 'shell_left_stitch',
        type: 'line',
        layer_id: 'outer_shell',
        start: { x: -108, y: -38 },
        end: { x: -108, y: 38 },
        line_role: 'stitch',
      },
      {
        id: 'shell_bottom_stitch',
        type: 'line',
        layer_id: 'outer_shell',
        start: { x: -108, y: 38 },
        end: { x: 108, y: 38 },
        line_role: 'stitch',
      },
      {
        id: 'shell_right_stitch',
        type: 'line',
        layer_id: 'outer_shell',
        start: { x: 108, y: 38 },
        end: { x: 108, y: -38 },
        line_role: 'stitch',
      },
      {
        id: 'shell_center_crease',
        type: 'line',
        layer_id: 'outer_shell',
        start: { x: 0, y: -48 },
        end: { x: 0, y: 48 },
        line_role: 'guide',
      },
      {
        id: 'wallet_center_fold',
        type: 'fold',
        start: { x: 0, y: -48 },
        end: { x: 0, y: 48 },
        name: 'Wallet Center Fold',
        direction: 'mountain',
        angle_deg: 138,
        max_angle_deg: 180,
        radius_mm: 2.4,
        thickness_mm: 1.8,
        neutral_axis_ratio: 0.5,
        stiffness: 0.38,
        clearance_mm: 3.2,
      },
      {
        id: 'bill_clearance_reference',
        type: 'rectangle',
        layer_id: 'clearance_guides',
        x: -78,
        y: -36,
        width: 156,
        height: 72,
        line_role: 'guide',
      },
      {
        id: 'left_card_clearance_reference',
        type: 'rectangle',
        layer_id: 'clearance_guides',
        x: -101.8,
        y: -27,
        width: 85.6,
        height: 54,
        line_role: 'guide',
      },
      {
        id: 'right_card_clearance_reference',
        type: 'rectangle',
        layer_id: 'clearance_guides',
        x: 16.2,
        y: -27,
        width: 85.6,
        height: 54,
        line_role: 'guide',
      },
      {
        id: 'bill_liner_outline',
        type: 'rectangle',
        layer_id: 'bill_liner',
        x: -110,
        y: -40,
        width: 220,
        height: 84,
        line_role: 'cut',
      },
      {
        id: 'bill_liner_left_stitch',
        type: 'line',
        layer_id: 'bill_liner',
        start: { x: -102, y: -32 },
        end: { x: -102, y: 36 },
        line_role: 'stitch',
      },
      {
        id: 'bill_liner_bottom_stitch',
        type: 'line',
        layer_id: 'bill_liner',
        start: { x: -102, y: 36 },
        end: { x: 102, y: 36 },
        line_role: 'stitch',
      },
      {
        id: 'bill_liner_right_stitch',
        type: 'line',
        layer_id: 'bill_liner',
        start: { x: 102, y: 36 },
        end: { x: 102, y: -32 },
        line_role: 'stitch',
      },
      {
        id: 'bill_liner_center_crease',
        type: 'line',
        layer_id: 'bill_liner',
        start: { x: 0, y: -40 },
        end: { x: 0, y: 44 },
        line_role: 'guide',
      },
      {
        id: 'left_pocket_left_edge',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -108, y: -34 },
        end: { x: -108, y: 43 },
        line_role: 'cut',
      },
      {
        id: 'left_pocket_bottom_edge',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -108, y: 43 },
        end: { x: -8, y: 43 },
        line_role: 'cut',
      },
      {
        id: 'left_pocket_right_edge',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -8, y: 43 },
        end: { x: -8, y: -34 },
        line_role: 'cut',
      },
      {
        id: 'left_pocket_thumb_cutout',
        type: 'arc',
        layer_id: 'left_stack',
        start: { x: -8, y: -34 },
        mid: { x: -58, y: -50 },
        end: { x: -108, y: -34 },
        line_role: 'cut',
      },
      {
        id: 'left_card_slot_upper',
        type: 'bezier',
        layer_id: 'left_stack',
        start: { x: -100, y: -12 },
        control: { x: -58, y: -24 },
        end: { x: -16, y: -12 },
        line_role: 'cut',
      },
      {
        id: 'left_card_slot_lower',
        type: 'bezier',
        layer_id: 'left_stack',
        start: { x: -100, y: 10 },
        control: { x: -58, y: -2 },
        end: { x: -16, y: 10 },
        line_role: 'cut',
      },
      {
        id: 'left_pocket_stitch_left',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -100, y: -24 },
        end: { x: -100, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'left_pocket_stitch_right',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -16, y: -24 },
        end: { x: -16, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'left_pocket_stitch_bottom',
        type: 'line',
        layer_id: 'left_stack',
        start: { x: -100, y: 35 },
        end: { x: -16, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'right_pocket_left_edge',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 8, y: -34 },
        end: { x: 8, y: 43 },
        line_role: 'cut',
      },
      {
        id: 'right_pocket_bottom_edge',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 8, y: 43 },
        end: { x: 108, y: 43 },
        line_role: 'cut',
      },
      {
        id: 'right_pocket_right_edge',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 108, y: 43 },
        end: { x: 108, y: -34 },
        line_role: 'cut',
      },
      {
        id: 'right_pocket_thumb_cutout',
        type: 'arc',
        layer_id: 'right_stack',
        start: { x: 108, y: -34 },
        mid: { x: 58, y: -50 },
        end: { x: 8, y: -34 },
        line_role: 'cut',
      },
      {
        id: 'right_card_slot_upper',
        type: 'bezier',
        layer_id: 'right_stack',
        start: { x: 16, y: -12 },
        control: { x: 58, y: -24 },
        end: { x: 100, y: -12 },
        line_role: 'cut',
      },
      {
        id: 'right_card_slot_lower',
        type: 'bezier',
        layer_id: 'right_stack',
        start: { x: 16, y: 10 },
        control: { x: 58, y: -2 },
        end: { x: 100, y: 10 },
        line_role: 'cut',
      },
      {
        id: 'right_pocket_stitch_left',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 16, y: -24 },
        end: { x: 16, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'right_pocket_stitch_right',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 100, y: -24 },
        end: { x: 100, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'right_pocket_stitch_bottom',
        type: 'line',
        layer_id: 'right_stack',
        start: { x: 16, y: 35 },
        end: { x: 100, y: 35 },
        line_role: 'stitch',
      },
      {
        id: 'wallet_title_label',
        type: 'text',
        layer_id: 'wallet_markings',
        position: { x: -36, y: 62 },
        value: 'Bifold Wallet',
        line_role: 'mark',
        font_size_mm: 6,
      },
    ],
  },
  {
    schema_version: 1,
    document_name: 'curved_pocket_panel',
    units: 'mm',
    layers: [
      { id: 'panel', name: 'Pocket Panel' },
      { id: 'stitching', name: 'Stitching' },
    ],
    entities: [
      {
        id: 'slot_curve',
        type: 'bezier',
        layer_id: 'panel',
        start: { x: -188, y: -50 },
        control: { x: -106, y: -88 },
        end: { x: -24, y: -50 },
        line_role: 'cut',
      },
      {
        id: 'stitch_run',
        type: 'line',
        layer_id: 'stitching',
        start: { x: -194, y: 106 },
        end: { x: -20, y: 106 },
        line_role: 'stitch',
      },
      {
        id: 'brand_mark',
        type: 'text',
        layer_id: 'panel',
        position: { x: -74, y: 122 },
        value: 'Heritage',
        transform: 'arch',
        radius_mm: 52,
        sweep_deg: 110,
      },
    ],
  },
] as const
