import type { UseEditorScreenShellsParams } from '../../editorScreenShellTypes'
import { useEditorWorkbenchController } from '../../controllers/useEditorWorkbenchController'
import {
  buildDocumentInspectorProps,
  buildPieceInspectorContentProps,
  buildSelectionInspectorProps,
} from '../../view-models/buildWorkbenchInspectorViewModels'
import {
  buildWorkbenchProps,
  buildWorkbenchThreeWorkspaceProps,
} from './buildWorkbenchShellViewModels'

export function useEditorScreenWorkbenchModels({
  resolvedThemeMode,
  documentState,
  uiState,
  selectionState,
  panelState,
  layerState,
  toolState,
  viewportState,
  workbenchShellState,
  screenRefs,
  derivedState,
  canvasController,
  patternPieceSelection,
  selectedEditableShape,
  actions,
}: UseEditorScreenShellsParams) {
  const {
    documentName,
    lineTypes,
    setLineTypes,
    setActiveLineTypeId,
    shapes,
    foldLines,
    sketchGroups,
    activeSketchGroupId,
    setActiveSketchGroupId,
    patternPieces,
    pieceLabels,
    piecePlacementLabels,
    piecePlacements3d,
    setPiecePlacements3d,
    seamConnections,
    setSeamConnections,
    seamAllowances,
    pieceNotches,
    setPieceNotches,
    snapSettings,
    setSnapSettings,
    showAnnotations,
    setShowAnnotations,
    tracingOverlays,
    setTracingOverlays,
    activeTracingOverlayId,
    setActiveTracingOverlayId,
    projectMemo,
    setProjectMemo,
    stitchThreadColor,
    setStitchThreadColor,
    threePreviewSettings,
    setThreePreviewSettings,
    avatars,
    setAvatars,
    threeTextureSource,
    setThreeTextureSource,
    threeTextureShapeIds,
    setThreeTextureShapeIds,
    showCanvasRuler,
    setShowCanvasRuler,
    showDimensions,
    setShowDimensions,
  } = documentState
  const {
    isMobileLayout,
    workbenchRibbonTab,
    setWorkbenchRibbonTab,
    workspaceMode,
    setWorkspaceMode,
    setSecondaryPreviewMode,
    displayUnit,
    setDisplayUnit,
    gridSpacing,
    setGridSpacing,
    sketchWorkspaceMode,
    setSketchWorkspaceMode,
    themeMode,
    setShowNestingModal,
    setShowChangeShapeSizeModal,
    setShowStitchSimulatorModal,
    setShowBoxStitchHelperModal,
    setShowBoxStitchModal,
    setShowWizardModal,
    setShowMandalaModal,
    setShowLetterStampModal,
    setShowPrecisionModal,
  } = uiState
  const { selectedShapeIds, setSelectedShapeIds } = selectionState
  const {
    setShowTracingModal,
    setShowAiBuilderModal,
    setShowHelpModal,
    setShowTemplateRepositoryModal,
    setShowPrintPreviewModal,
  } = panelState
  const {
    layers,
    setLayers,
    activeLayerId,
    setActiveLayerId,
    frontLayerColor,
    setFrontLayerColor,
    backLayerColor,
    setBackLayerColor,
    layerColorOverrides,
  } = layerState
  const { tool, clearDraft, setActiveTool } = toolState
  const { viewport } = viewportState
  const {
    shellRef,
    showPeek,
    effectiveSecondaryPreviewMode,
    effectiveLayout,
    setActiveInspectorTab,
    handleBrowserResizeStart,
    handlePeekResizeStart,
    handleInspectorResizeStart,
    splitterWidth,
    toolRailWidth,
  } = workbenchShellState
  const { fileInputRef, svgInputRef } = screenRefs
  const {
    activeLayer,
    activeLineType,
    patternPiecesById,
    shapeCountsByLineType,
    selectedShapeCount,
    selectedShapeIdSet,
    selectedStitchHole,
    selectedHardwareMarker,
    canUndo,
    canRedo,
    assemblyShapes,
    visibleStitchHoles,
    workspaceShapes,
    workspaceStitchHoles,
    layerColorsById,
  } = derivedState
  const {
    selectedShapes,
    selectedPatternPiece,
    selectedPieceGrainline,
    selectedPieceLabel,
    selectedPatternLabel,
    selectedPieceSeamAllowance,
    selectedPieceSeamConnections,
    selectedPieceNotches,
    selectedPiecePlacementLabels,
    selectedPieceInternalShapeIdSet,
    selectedPatternPieceEdgeCount,
    selectedPieceAvailableInternalShapes,
  } = patternPieceSelection
  const { handleFitView, handleResetView } = canvasController
  const {
    documentCommands,
    exportActions,
    fileActions,
    historyActions,
    selectionActions,
    lineTypeActions,
    layerColorActions,
    constraintActions,
    patternPieceCommands,
    hardwareMarkerActions,
    stitchActions,
    geometryActions,
    creationController,
    themeActions,
  } = actions
  const {
    handleUpdateSelectedShapePoint,
    handleUpdateSelectedStitchHole,
    updateFoldLine,
  } = documentCommands
  const { handleExportSvg, handleExportPdf, handleExportDxf } = exportActions
  const { handleSaveJson, handleLoadPreset } = fileActions
  const { handleUndo, handleRedo } = historyActions
  const {
    handleCopySelection,
    handlePasteClipboard,
    handleDeleteSelection,
    handleMoveSelectionByDistance,
    handleRotateSelection,
    handleScaleSelection,
  } = selectionActions
  const {
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleCreateOffsetGeometryFromSelection,
  } = constraintActions
  const {
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleIsolateActiveLineType,
    handleSelectShapesByActiveLineType,
    handleShowAllLineTypes,
    handleUpdateActiveLineTypeColor,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
  } = lineTypeActions
  const {
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  } = layerColorActions
  const {
    ensurePatternPieceSupportRecords,
    openSelectedPatternPieceInspector,
    handleCreatePatternPieceFromSelection,
    handleUpdateSelectedPatternPiece,
    handleToggleSelectedPieceInternalShape,
    updateSelectedLabel,
    handleUpdateSelectedPieceGrainline,
    handleUpdateSelectedPieceSeamAllowance,
    handleUpdateSelectedPieceSeamConnection,
    handleUpdateSelectedPieceNotch,
    handleAddSelectedPiecePlacementLabel,
    handleUpdateSelectedPiecePlacementLabel,
    handleDeleteSelectedPiecePlacementLabel,
  } = patternPieceCommands
  const { handleDeleteSelectedHardwareMarker, handleUpdateSelectedHardwareMarker } = hardwareMarkerActions
  const {
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleCountStitchHolesOnSelectedShapes,
    handleClearAllStitchHoles,
  } = stitchActions
  const {
    handleConvertArcToBezier,
    handleExtendOrTrimLines,
    handleMirrorShapes,
    handleMakeBezierCpSymmetric,
    handleToggleBezierOffsetLines,
  } = geometryActions
  const {
    handleApplyTextDefaultsToSelection,
    handleExtractSelectedBoxStitchSources,
    handleClearSelectedBoxStitchSources,
    handleOpenBoxStitchHelperModal,
    handleMarkSelectedStitchHoleAsEnd,
    handleClearSelectedStitchHoleEnd,
  } = creationController
  const { handleSetThemeMode } = themeActions

  const workbenchController = useEditorWorkbenchController({
    documentName,
    patternPieces,
    patternPiecesById,
    pieceLabels,
    seamAllowances,
    pieceNotches,
    piecePlacementLabels,
    seamConnections,
    layers,
    activeLayerId,
    sketchGroups,
    activeSketchGroupId,
    tracingOverlays,
    activeTracingOverlayId,
    avatars,
    threeTextureSource,
    selectedShapes,
    selectedPatternPiece,
    selectedStitchHole,
    selectedHardwareMarker,
    selectedShapeCount,
    selectedShapeIdSet,
    canUndo,
    canRedo,
    workbenchRibbonTab,
    setActiveInspectorTab,
    isMobileLayout,
    workspaceMode,
    handleSaveJson,
    handleUndo,
    handleRedo,
    setShowHelpModal,
    handleFitView,
    handleResetView,
    setShowCanvasRuler,
    setShowDimensions,
    handleLoadPreset,
    setShowAnnotations,
    handleCopySelection,
    handlePasteClipboard,
    handleDeleteSelection,
    handleMoveSelectionByDistance,
    handleRotateSelection,
    handleScaleSelection,
    handleCreatePatternPieceFromSelection,
    openSelectedPatternPieceInspector,
    handleApplySeamAllowanceToSelection,
    setShowNestingModal,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleCountStitchHolesOnSelectedShapes,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleClearAllStitchHoles,
    fileInputRef,
    svgInputRef,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    setShowPrintPreviewModal,
    setShowTemplateRepositoryModal,
    setShowTracingModal,
    setShowAiBuilderModal,
    handleConvertArcToBezier,
    handleExtendOrTrimLines,
    handleMirrorShapes,
    handleMakeBezierCpSymmetric,
    handleToggleBezierOffsetLines,
    setShowChangeShapeSizeModal,
    setShowStitchSimulatorModal,
    setShowBoxStitchHelperModal,
    setShowBoxStitchModal,
    setShowWizardModal,
    setShowMandalaModal,
    setShowLetterStampModal,
    ensurePatternPieceSupportRecords,
    setSelectedShapeIds,
    setActiveLayerId,
    clearDraft,
    setActiveSketchGroupId,
    setActiveTracingOverlayId,
    setLayers,
    setTracingOverlays,
    setSecondaryPreviewMode,
    setWorkspaceMode,
  })
  const shouldLoadThreeWorkbench = workspaceMode === '3d'
  const selectionInspectorProps = buildSelectionInspectorProps({
    context: workbenchController.selectionContext,
    selectedShapeCount,
    selectedEditableShape,
    selectedStitchHole,
    selectedHardwareMarker,
    shapeCount: shapes.length,
    layerCount: layers.length,
    handleAlignSelection,
    handleAlignSelectionToGrid,
    handleCreateOffsetGeometryFromSelection,
    handleOpenBoxStitchHelperModal,
    handleBevelSelectedCorner,
    handleRoundSelectedCorner,
    handleAddEdgeConstraintFromSelection,
    handleAddAlignConstraintsFromSelection,
    handleApplyConstraints,
    handleCreatePatternPieceFromSelection,
    openSelectedPatternPieceInspector,
    canOpenPieceTab: selectedPatternPiece !== null,
    handleApplySeamAllowanceToSelection,
    handleClearSeamAllowanceOnSelection,
    handleApplyTextDefaultsToSelection,
    handleExtractSelectedBoxStitchSources,
    handleClearSelectedBoxStitchSources,
    handleUpdateSelectedShapePoint,
    handleUpdateSelectedStitchHole,
    handleMarkSelectedStitchHoleAsEnd,
    handleClearSelectedStitchHoleEnd,
    handleUpdateSelectedHardwareMarker,
    handleDeleteSelectedHardwareMarker,
  })
  const pieceInspectorContentProps = buildPieceInspectorContentProps({
    selectedPatternPiece,
    selectedPieceGrainline,
    selectedPieceLabel,
    selectedPatternLabel,
    selectedPieceSeamAllowance,
    selectedPieceSeamConnections,
    selectedPieceNotches,
    selectedPiecePlacementLabels,
    selectedPatternPieceEdgeCount,
    selectedPieceAvailableInternalShapes,
    selectedPieceInternalShapeIdSet,
    handleUpdateSelectedPatternPiece,
    handleToggleSelectedPieceInternalShape,
    handleUpdateSelectedPieceGrainline,
    updateSelectedLabel,
    handleUpdateSelectedPieceSeamAllowance,
    handleUpdateSelectedPieceSeamConnection,
    setSeamConnections,
    handleUpdateSelectedPieceNotch,
    setPieceNotches,
    handleAddSelectedPiecePlacementLabel,
    handleUpdateSelectedPiecePlacementLabel,
    handleDeleteSelectedPiecePlacementLabel,
  })
  const documentInspectorProps = buildDocumentInspectorProps({
    displayUnit,
    setDisplayUnit,
    gridSpacing,
    setGridSpacing,
    showCanvasRuler,
    setShowCanvasRuler,
    showDimensions,
    setShowDimensions,
    showAnnotations,
    setShowAnnotations,
    sketchWorkspaceMode,
    setSketchWorkspaceMode,
    themeMode,
    handleSetThemeMode,
    snapSettings,
    setSnapSettings,
    projectMemo,
    setProjectMemo,
    activeLineType,
    lineTypes,
    shapeCountsByLineType,
    selectedShapeCount,
    handleAssignSelectedToActiveLineType,
    handleClearShapeSelection,
    handleIsolateActiveLineType,
    handleSelectShapesByActiveLineType,
    setActiveLineTypeId,
    handleShowAllLineTypes,
    setLineTypes,
    handleUpdateActiveLineTypeColor,
    handleUpdateActiveLineTypeRole,
    handleUpdateActiveLineTypeStyle,
    layers,
    layerColorsById,
    layerColorOverrides,
    frontLayerColor,
    backLayerColor,
    setFrontLayerColor,
    setBackLayerColor,
    handleSetLayerColorOverride,
    handleClearLayerColorOverride,
    handleResetLayerColors,
  })
  const workbenchProps = buildWorkbenchProps({
    controller: workbenchController,
    shellRef,
    workspaceMode,
    secondaryPreviewMode: effectiveSecondaryPreviewMode,
    showPeek,
    browserWidth: effectiveLayout.browserWidth,
    inspectorWidth: effectiveLayout.inspectorWidth,
    peekWidth: effectiveLayout.peekWidth,
    splitterWidth,
    toolRailWidth,
    activeRibbonTab: workbenchRibbonTab,
    themeMode,
    onSetRibbonTab: setWorkbenchRibbonTab,
    onSetThemeMode: handleSetThemeMode,
    setLayers,
    tool,
    onSetActiveTool: setActiveTool,
    activeInspectorTab: effectiveLayout.activeInspectorTab,
    onSetActiveInspectorTab: setActiveInspectorTab,
    onStartBrowserResize: handleBrowserResizeStart,
    onStartPeekResize: handlePeekResizeStart,
    onStartInspectorResize: handleInspectorResizeStart,
    zoomScale: viewport.scale,
    displayUnit,
    activeLayer,
    activeLineType,
    onTogglePrecision: () => setShowPrecisionModal((previous) => !previous),
  })
  const workbenchThreeWorkspaceProps = buildWorkbenchThreeWorkspaceProps({
    workspaceMode,
    shapes: sketchWorkspaceMode === 'assembly' ? assemblyShapes : workspaceShapes,
    selectedShapeIds,
    stitchHoles: sketchWorkspaceMode === 'assembly' ? visibleStitchHoles : workspaceStitchHoles,
    stitchThreadColor,
    onSetStitchThreadColor: setStitchThreadColor,
    patternPieces,
    piecePlacements3d,
    seamConnections,
    threePreviewSettings,
    avatars,
    onSetPiecePlacements3d: setPiecePlacements3d,
    onSetThreePreviewSettings: setThreePreviewSettings,
    onSetAvatars: setAvatars,
    threeTextureSource,
    onSetThreeTextureSource: setThreeTextureSource,
    threeTextureShapeIds,
    onSetThreeTextureShapeIds: setThreeTextureShapeIds,
    foldLines,
    layers,
    lineTypes,
    themeMode: resolvedThemeMode,
    onUpdateFoldLine: updateFoldLine,
  })

  return {
    workbenchController,
    shouldLoadThreeWorkbench,
    selectionInspectorProps,
    pieceInspectorContentProps,
    documentInspectorProps,
    workbenchProps,
    workbenchThreeWorkspaceProps,
  }
}
