import type { DocFile } from './cad-types'

export const SAMPLE_WALLET_DOC: DocFile = {
  version: 1,
  units: 'mm',
  layers: [
    {
      id: 'layer-pattern',
      name: 'Pattern',
      visible: true,
      locked: false,
    },
    {
      id: 'layer-stitch-guides',
      name: 'Stitch Guides',
      visible: true,
      locked: false,
    },
  ],
  activeLayerId: 'layer-pattern',
  objects: [
    {
      id: 'outline-top',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: -220, y: -140 },
      end: { x: 220, y: -140 },
    },
    {
      id: 'outline-right',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: 220, y: -140 },
      end: { x: 220, y: 140 },
    },
    {
      id: 'outline-bottom',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: 220, y: 140 },
      end: { x: -220, y: 140 },
    },
    {
      id: 'outline-left',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: -220, y: 140 },
      end: { x: -220, y: -140 },
    },
    {
      id: 'left-slot-top',
      type: 'bezier',
      layerId: 'layer-pattern',
      start: { x: -200, y: -50 },
      control: { x: -112, y: -92 },
      end: { x: -20, y: -50 },
    },
    {
      id: 'right-slot-top',
      type: 'bezier',
      layerId: 'layer-pattern',
      start: { x: 20, y: -50 },
      control: { x: 112, y: -92 },
      end: { x: 200, y: -50 },
    },
    {
      id: 'left-pocket-mouth',
      type: 'arc',
      layerId: 'layer-pattern',
      start: { x: -198, y: 86 },
      mid: { x: -110, y: 34 },
      end: { x: -22, y: 86 },
    },
    {
      id: 'right-pocket-mouth',
      type: 'arc',
      layerId: 'layer-pattern',
      start: { x: 22, y: 86 },
      mid: { x: 110, y: 34 },
      end: { x: 198, y: 86 },
    },
    {
      id: 'stitch-guide-top',
      type: 'line',
      layerId: 'layer-stitch-guides',
      start: { x: -200, y: -122 },
      end: { x: 200, y: -122 },
    },
    {
      id: 'stitch-guide-right',
      type: 'line',
      layerId: 'layer-stitch-guides',
      start: { x: 200, y: -122 },
      end: { x: 200, y: 122 },
    },
    {
      id: 'stitch-guide-bottom',
      type: 'line',
      layerId: 'layer-stitch-guides',
      start: { x: 200, y: 122 },
      end: { x: -200, y: 122 },
    },
    {
      id: 'stitch-guide-left',
      type: 'line',
      layerId: 'layer-stitch-guides',
      start: { x: -200, y: 122 },
      end: { x: -200, y: -122 },
    },
    {
      id: 'card-divider-left',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: -96, y: -50 },
      end: { x: -96, y: 96 },
    },
    {
      id: 'card-divider-right',
      type: 'line',
      layerId: 'layer-pattern',
      start: { x: 96, y: -50 },
      end: { x: 96, y: 96 },
    },
  ],
  foldLines: [
    {
      id: 'wallet-center-fold',
      name: 'Wallet Center Fold',
      start: { x: 0, y: -140 },
      end: { x: 0, y: 140 },
      angleDeg: 58,
      maxAngleDeg: 180,
    },
  ],
}
