import type { UseEditorScreenShellsParams } from '../../editorScreenShellTypes'
import { buildCanvasPaneParams } from './buildCanvasPaneParams'

export function buildEditorScreenCanvasPaneParams({
  resolvedThemeMode,
  documentState,
  uiState,
  selectionState,
  panelState,
  layerState,
  toolState,
  viewportState,
  screenRefs,
  derivedState,
  canvasController,
  patternPieceSelection,
  printPreviewState,
  previewElement,
  outlineChains,
  stitchSimulatorSettings,
  actions,
  highlightActiveLayerId,
  drawEdges,
  drawFirstPos,
}: UseEditorScreenShellsParams & {
  highlightActiveLayerId?: string | null
  drawEdges?: boolean
  drawFirstPos?: boolean
}) {
  const {
    shapes,
    lineTypes,
    foldLines,
    dimensionLines,
    leatherImageFills,
    tracingOverlays,
    setTracingOverlays,
    backdrops,
    setBackdrops,
    activeBackdropId,
    setActiveBackdropId,
    showAnnotations,
    showCanvasRuler,
    showDimensions,
  } = documentState
  const {
    showGrid,
    gridBackgroundMode,
    displayUnit,
    gridSpacing,
    constraintSuggestions,
    sketchWorkspaceMode,
    legendMode,
    setLegendMode,
    leatherSimEnabled,
  } = uiState
  const { selectedStitchHoleId, selectedHardwareMarkerId } = selectionState
  const { showPrintAreas } = panelState
  const { layers } = layerState
  const { tool, showStitchSequenceLabels } = toolState
  const { viewport } = viewportState
  const { svgRef } = screenRefs
  const {
    lineTypesById,
    selectedShapeIdSet,
    selectedStitchHole,
    workspaceEditableShapes,
    workspaceLinkedShapes,
    workspaceStitchHoles,
    workspaceHardwareMarkers,
    seamGuides,
    annotationLabels,
    pieceGrainlineSegments,
    pieceNotchLines,
    piecePlacementGuides,
    layerColorsById,
    stackLegendEntries,
    displayLayerColorsById,
    fallbackLayerStroke,
    cutStrokeColor,
    stitchStrokeColor,
    foldStrokeColor,
  } = derivedState
  const { pieceEdgeLabels } = patternPieceSelection
  const { printOutputPlan } = printPreviewState
  const {
    handleZoomStep,
    handleFitView,
    handleResetView,
    handlePointerDown,
    handleShapePointerDown,
    handleShapeHandlePointerDown,
    handleStitchHolePointerDown,
    handleHardwarePointerDown,
    handlePointerMove,
    handlePointerUp,
    interactionPreview,
  } = canvasController
  const {
    selectionActions,
    geometryActions,
    creationController,
  } = actions
  const {
    handleDuplicateSelection,
    handleDeleteSelection,
    handleSendSelectionToBack,
    handleBringSelectionToFront,
  } = selectionActions
  const {
    handleConvertSelectionToPath,
    handleMakeBezierCpFlat,
    handleMakeBezierCpSameLength,
    handleMakeBezierCpSymmetric,
    handleSmoothBezierJointAtControl,
  } = geometryActions
  const {
    stitchSimulatorResult,
    handleMarkSelectedStitchHoleAsEnd,
    handleClearSelectedStitchHoleEnd,
  } = creationController
  const effectiveGridBackgroundMode = gridBackgroundMode === 'theme' ? resolvedThemeMode : gridBackgroundMode

  return buildCanvasPaneParams({
    svgRef,
    onPointerDown: handlePointerDown,
    onPointerMove: handlePointerMove,
    onPointerUp: handlePointerUp,
    showGrid,
    gridBackgroundMode: effectiveGridBackgroundMode,
    setTracingOverlays,
    setBackdrops,
    setActiveBackdropId,
    shapes,
    selectedStitchHole,
    handleBringSelectionToFront,
    handleSendSelectionToBack,
    handleDuplicateSelection,
    handleConvertSelectionToPath,
    handleDeleteSelection,
    handleMakeBezierCpFlat,
    handleMakeBezierCpSameLength,
    handleMakeBezierCpSymmetric,
    handleClearSelectedStitchHoleEnd,
    handleMarkSelectedStitchHoleAsEnd,
    viewport,
    displayUnit,
    gridSpacing,
    showCanvasRuler,
    showDimensions,
    handleZoomStep,
    onFitView: handleFitView,
    onResetView: handleResetView,
    tracingOverlays,
    leatherImageFills,
    backdrops,
    activeBackdropId,
    showPrintAreas,
    dimensionLines,
    printPlan: printOutputPlan,
    seamGuides,
    pieceEdgeLabels,
    showAnnotations,
    pieceGrainlineSegments,
    pieceNotchLines,
    piecePlacementGuides,
    visibleShapes: workspaceEditableShapes,
    linkedShapes: workspaceLinkedShapes,
    sketchWorkspaceMode,
    lineTypes,
    lineTypesById,
    selectedShapeIdSet,
    stitchStrokeColor,
    foldStrokeColor,
    cutStrokeColor,
    displayLayerColorsById,
    onShapePointerDown: handleShapePointerDown,
    onShapeHandlePointerDown: handleShapeHandlePointerDown,
    onShapeHandleDoubleClick: (shapeId: string, pointKey: 'start' | 'mid' | 'control' | 'end') => {
      if (pointKey !== 'control') return
      handleSmoothBezierJointAtControl(shapeId)
    },
    tool,
    visibleStitchHoles: workspaceStitchHoles,
    selectedStitchHoleId,
    showStitchSequenceLabels,
    onStitchHolePointerDown: handleStitchHolePointerDown,
    stitchSimulatorResult,
    stitchSimulatorSettings,
    hideRawStitchHoles: leatherSimEnabled && stitchSimulatorSettings.showSimulatorPattern,
    visibleHardwareMarkers: workspaceHardwareMarkers,
    selectedHardwareMarkerId,
    onHardwarePointerDown: handleHardwarePointerDown,
    foldLines,
    annotationLabels,
    constraintSuggestions,
    previewElement,
    interactionPreview,
    showLayerLegend: false,
    legendMode,
    onSetLegendMode: setLegendMode,
    layers,
    layerColorsById,
    fallbackLayerStroke,
    stackLegendEntries,
    outlineChains,
    highlightActiveLayerId,
    drawEdges,
    drawFirstPos,
  })
}
