import type { UseEditorScreenShellsParams } from '../../editorScreenShellTypes'
import { useEditorTopbarViewModel } from '../../view-models/useEditorTopbarViewModel'

export type EditorScreenTopbarLayout = {
  topbarClassName: string
  showToolSection: boolean
  showZoomSection: boolean
  showEditSection: boolean
  showLineTypeSection: boolean
  showStitchSection: boolean
  showLayerSection: boolean
  showFileSection: boolean
}

type UseEditorScreenTopbarPropsParams = UseEditorScreenShellsParams & {
  layout: EditorScreenTopbarLayout
}

export function useEditorScreenTopbarProps({
  documentState,
  uiState,
  selectionState,
  panelState,
  screenRefs,
  derivedState,
  actions,
  layout,
}: UseEditorScreenTopbarPropsParams) {
  const {
    shapes,
    setShapes,
    foldLines,
    setFoldLines,
    stitchHoles,
    setStitchHoles,
    setHardwareMarkers,
    setDimensionLines,
    setSketchGroups,
    setActiveSketchGroupId,
    setPatternPieces,
    setPieceInterfaces,
    setAssemblyConnections,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setConstraints,
    setBackdrops,
    setActiveBackdropId,
    setTracingOverlays,
  } = documentState
  const {
    setStatus,
    customRotationPivot,
    customSnapPoint,
    setShowFontListModal,
    setShowWizardModal,
    setShowBackdropModal,
    setShowOptionsModal,
    setShowLengthAdjustModal,
    setShowDimensionInspectorModal,
    setShowMoveCopyDistanceModal,
    setMoveCopyDistanceMode,
  } = uiState
  const {
    selectedShapeIds,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
  } = selectionState
  const { setShowLayerColorModal } = panelState
  const { fileInputRef, svgInputRef, tracingInputRef, translationInputRef } = screenRefs
  const {
    activeLayer,
    layerStackLevels,
    selectedShapeCount,
    selectedStitchHoleCount,
    selectedShapeIdSet,
    selectedStitchHole,
    canUndo,
    canRedo,
  } = derivedState
  const {
    editorStateActions,
    documentCommands,
    exportActions,
    fileActions,
    historyActions,
    selectionActions,
    transformActions,
    layerActions,
    lineTypeActions,
    stitchActions,
    geometryActions,
    mobileActions,
    themeActions,
  } = actions
  const { resetDocument } = editorStateActions
  const { handleEnableStitchOnSelection, handleDisableStitchOnSelection } = documentCommands
  const { handleExportSvg, handleExportPdf, handleExportDxf, handleExportLaserSvg } = exportActions
  const { handleSaveJson, handleLoadPreset, handleOpenInNewTab } = fileActions
  const { handleUndo, handleRedo } = historyActions
  const {
    handleCopySelection,
    handleCutSelection,
    handlePasteClipboard,
    handleSelectAllShapes,
    handleDuplicateSelection,
    handleDeleteSelection,
    handleGroupSelection,
    handleUngroupSelection,
    handleRotateSelection,
    handleScaleSelection,
    handleMoveSelectionBackward,
    handleMoveSelectionForward,
    handleSendSelectionToBack,
    handleBringSelectionToFront,
  } = selectionActions
  const {
    handleAlignSelectionToEdge,
    handleFlipSelection,
    handleReverseSelectedPaths,
    handleOpenSpecifyRotationModal,
    handleOpenSpecifyScaleModal,
    handleSetAsRotationCenter,
    handleClearRotationCenter,
    handleSetAsSnapPoint,
    handleClearSnapPoint,
    handleMakeSelectedLineHorizontal,
    handleMakeSelectedLineVertical,
  } = transformActions
  const {
    handleAddLayer,
    handleRenameActiveLayer,
    handleToggleLayerVisibility,
    handleToggleLayerLock,
    handleMoveLayer,
    handleDeleteLayer,
    handleShowAllLayers,
    handleHideOtherLayers,
    handleMergeActiveLayerIntoBelow,
    handleFlattenAllLayers,
    handleActivateLayerOfSelectedShape,
    handleDuplicateSelectedShapesOnBelowLayer,
    handleMoveSelectedShapesToLayerBelow,
    handleMoveSelectedShapesToAnotherLayer,
    handleHighlightShapesOnCurrentLayer,
    handleToggleLayerIgnored,
    handleToggleIndependentLayer,
  } = layerActions
  const { handleToggleActiveLineTypeVisibility } = lineTypeActions
  const {
    handleAutoPlacePreferredPitchStitchHoles,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleAutoPlaceEvenlySpacedStitchHoles,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleFixStitchHoleOrderFromSelected,
    handleCountStitchHolesOnSelectedShapes,
    handleDeleteStitchHolesOnSelectedShapes,
    handleChangeStitchHoleShapeOnSelectedShapes,
    handleClearAllStitchHoles,
  } = stitchActions
  const {
    handleEditSelectedLineAngle,
    handleDeleteDuplicates,
    handleSplitIntoN,
    handleFilletSelectedCorner,
    handleDistanceMarkSelectedPath,
    handleConvertSelectionToPath,
    handleNotchSelectedShape,
    handleLineSymmetry,
    handleCenterLineBetweenSelection,
    handleDrawBoundaryAroundSelection,
  } = geometryActions
  const { handleRunMobileLayerAction, handleRunMobileFileAction } = mobileActions
  const { handleSetThemeMode } = themeActions
  const handleOpenMoveCopyDistanceModal = (mode: 'move' | 'copy') => {
    if (selectedShapeCount === 0) {
      setStatus('Select one or more shapes first')
      return
    }
    setMoveCopyDistanceMode(mode)
    setShowMoveCopyDistanceModal(true)
  }

  return useEditorTopbarViewModel({
    tracingInputRef,
    translationInputRef,
    shapes,
    stitchHoles,
    foldLines,
    selectedShapeIds,
    selectedShapeIdSet,
    setShapes,
    setStitchHoles,
    setFoldLines,
    setSelectedShapeIds,
    setSelectedStitchHoleId,
    setSelectedHardwareMarkerId,
    setHardwareMarkers,
    setDimensionLines,
    setSketchGroups,
    setActiveSketchGroupId,
    setPatternPieces,
    setPieceInterfaces,
    setAssemblyConnections,
    setPieceGrainlines,
    setPieceLabels,
    setPiecePlacementLabels,
    setPiecePlacements3d,
    setSeamConnections,
    setSeamAllowances,
    setPieceNotches,
    setConstraints,
    setBackdrops,
    setActiveBackdropId,
    setTracingOverlays,
    setStatus,
    resetDocument,
    setShowFontListModal,
    setShowWizardModal,
    setShowBackdropModal,
    setShowOptionsModal,
    setShowLengthAdjustModal,
    setShowDimensionInspectorModal,
    handleEditSelectedLineAngle,
    handleDeleteDuplicates,
    handleSplitIntoN,
    handleFilletSelectedCorner,
    handleDistanceMarkSelectedPath,
    handleConvertSelectionToPath,
    handleNotchSelectedShape,
    topbarClassName: layout.topbarClassName,
    selectedShapeCount,
    selectedStitchHoleCount,
    showToolSection: layout.showToolSection,
    handleLoadPreset,
    handleSetThemeMode,
    showZoomSection: layout.showZoomSection,
    showEditSection: layout.showEditSection,
    canUndo,
    canRedo,
    handleUndo,
    handleRedo,
    handleCopySelection,
    handleCutSelection,
    handlePasteClipboard,
    canPaste: true,
    handleSelectAllShapes,
    handleDuplicateSelection,
    handleDeleteSelection,
    handleGroupSelection,
    handleUngroupSelection,
    handleMoveSelectionByDistance: () => handleOpenMoveCopyDistanceModal('move'),
    handleCopySelectionByDistance: () => handleOpenMoveCopyDistanceModal('copy'),
    handleRotateSelection,
    handleScaleSelection,
    handleAlignSelectionToEdge,
    handleFlipSelection,
    handleReverseSelectedPaths,
    handleOpenSpecifyRotationModal,
    handleOpenSpecifyScaleModal,
    handleSetAsRotationCenter,
    handleClearRotationCenter,
    handleSetAsSnapPoint,
    handleClearSnapPoint,
    handleMakeSelectedLineHorizontal,
    handleMakeSelectedLineVertical,
    hasCustomRotationPivot: customRotationPivot !== null,
    hasCustomSnapPoint: customSnapPoint !== null,
    handleLineSymmetry,
    handleCenterLineBetweenSelection,
    handleDrawBoundaryAroundSelection,
    handleActivateLayerOfSelectedShape,
    handleDuplicateSelectedShapesOnBelowLayer,
    handleMoveSelectedShapesToLayerBelow,
    handleMoveSelectedShapesToAnotherLayer,
    handleHighlightShapesOnCurrentLayer,
    handleToggleLayerIgnored,
    handleToggleIndependentLayer,
    handleEnableStitchOnSelection,
    handleDisableStitchOnSelection,
    handleMoveSelectionBackward,
    handleMoveSelectionForward,
    handleSendSelectionToBack,
    handleBringSelectionToFront,
    showLineTypeSection: layout.showLineTypeSection,
    handleToggleActiveLineTypeVisibility,
    showStitchSection: layout.showStitchSection,
    handleAutoPlacePreferredPitchStitchHoles,
    handleAutoPlaceFixedPitchStitchHoles,
    handleAutoPlaceVariablePitchStitchHoles,
    handleAutoPlaceEvenlySpacedStitchHoles,
    handleResequenceSelectedStitchHoles,
    handleSelectNextStitchHole,
    handleFixStitchHoleOrderFromSelected,
    handleCountStitchHolesOnSelectedShapes,
    handleDeleteStitchHolesOnSelectedShapes,
    handleChangeStitchHoleShapeOnSelectedShapes,
    handleClearAllStitchHoles,
    stitchHolesLength: stitchHoles.length,
    hasSelectedStitchHole: selectedStitchHole !== null,
    showLayerSection: layout.showLayerSection,
    activeLayer,
    layerStackLevels,
    handleRunMobileLayerAction,
    handleAddLayer,
    handleRenameActiveLayer,
    handleToggleLayerVisibility,
    handleToggleLayerLock,
    handleMoveLayer,
    handleDeleteLayer,
    handleShowAllLayers,
    handleHideOtherLayers,
    handleMergeActiveLayerIntoBelow,
    handleFlattenAllLayers,
    setShowLayerColorModal,
    showFileSection: layout.showFileSection,
    handleRunMobileFileAction,
    handleSaveJson,
    fileInputRef,
    svgInputRef,
    handleExportSvg,
    handleExportPdf,
    handleExportDxf,
    handleExportLaserSvg,
    handleOpenInNewTab,
  })
}
